export const SUPPORTED_LOCALES = ["en", "es", "fr"]

export const LOCALE_LABELS = {
  en: "English",
  es: "Español",
  fr: "Français",
}

export const LOCALE_STORAGE_KEY = "locale"

export const DEFAULT_LOCALE = "en"

export const LOCALIZABLE_PUBLIC_PATHS = [
  "/settings",
  "/products",
  "/products/smart-search",
  "/products/recent-purchases",
  "/categories",
  "/catalog/sidebar",
  "/home",
  "/storefront",
  "/banners",
  "/brand-banners",
  "/monthly-promotions",
  "/promotions",
  "/regions",
  "/contact-faqs",
  "/gift-items",
  "/ecommerce-settings/home-benefits",
  "/ecommerce-settings/currency",
  "/search/suggestions",
]

export const LOCALIZABLE_AUTH_PATHS = [
  "/login",
  "/register",
  "/me",
  "/forgot-password",
  "/reset-password",
]

export const LOCALIZABLE_PRIVATE_PATHS = [
  "/cart",
  "/checkout",
  "/account",
  "/me/locale",
]

export const messages = {
  en: {
    addToCart: "Add to cart",
    addingToCart: "Adding...",
    addToWishlist: "Add to list",
    askQuestion: "Ask a question",
    attributes: "Attributes",
    automaticInCart: "Automatic in cart",
    active: "Active",
    activePromotions: "Active promotions",
    appliesPromotions: "Applies promotions",
    artisanSelectionTitle: "Selection from our artisans",
    addedToCart: "Product added to cart.",
    addedToFavorites: "Product added to favorites.",
    addFavorite: "Add to favorites",
    baseSku: "Base SKU",
    brand: "Brand",
    brands: "Brands",
    cart: "Cart",
    cartAddedProductsMeta: "{products} products · {pieces} pieces",
    cartAppliedPromotion: "Applied promo",
    cartAvailable: "Available",
    cartClear: "Clear cart",
    cartClearing: "Clearing...",
    cartContinueCheckout: "Continue to checkout",
    cartEmptyText: "You have not added products yet. Explore the catalog and start your order.",
    cartEmptyTitle: "Your cart is empty",
    cartGiftPending: "{count} gift(s) pending selection",
    cartGiftSelected: "Selected gift",
    cartGoToProducts: "Go to products",
    cartInsufficientStock: "Insufficient stock",
    cartLoadingText: "Please wait while we load your products.",
    cartLoadingTitle: "Loading cart...",
    cartNoProductsFound: "We could not find products in your cart",
    cartNoProductsFoundText: "Try another term or adjust your search.",
    cartProcessOrder: "Process order",
    cartQuickWholesaleOrder: "Quick wholesale order",
    cartRegionalSplitsTitle: "Regional distribution",
    cartRegionalSplitsText: "Estimated split by regional center.",
    cartRegionalSource: "Regional center: {region}",
    commissionEstimated: "Estimated commission",
    netEstimated: "Estimated net",
    cartRemove: "Remove",
    cartRemoveSelection: "Remove selected",
    cartRemoving: "Removing...",
    cartReviewAvailability: "Check availability",
    cartSaveList: "Save to list",
    cartSearchPlaceholder: "Search within cart",
    cartSelectProduct: "Select {name}",
    cartShowingProducts: "Showing {shown} of {total} products",
    cartUnitPrice: "Unit price",
    cartClearSuccess: "Cart cleared successfully.",
    cartCouponApplied: "Coupon applied to cart",
    cartCouponCodePrompt: "Add a promo code",
    cartCouponTitle: "Coupon",
    cartInvalidCoupon: "Not valid",
    cartApplyCoupon: "Apply",
    cartApplying: "Applying...",
    cartRemoveCoupon: "Remove",
    cartRemovingSelection: "Removing...",
    cartRecovered: "Cart recovered successfully.",
    cartRemoveProductError: "Could not remove the product.",
    cartRemoveSelectedSuccess: "Selected products removed successfully.",
    cartRemoveSelectedError: "Could not remove the selected products.",
    cartSelectAtLeastOne: "Select at least one product.",
    cartGiftChosen: "Gift selected",
    cartGiftChoosePending: "Select your pending gift before continuing to checkout.",
    cartGiftAccounting: "{units} billed gift(s) at {unitPrice} each ({lineTotal})",
    cartGiftItems: "{units} promotional gift item(s){names}",
    cartGiftAvailable: "Gift available",
    cartChooseGift: "Choose your gift to complete this promotion.",
    cartSelectedGiftLabel: "Selected gift",
    cartGiftSku: "Gift SKU #{sku} · Quantity {quantity}",
    cartGiftSkuAdded: "The gift SKU is already in your cart.",
    cartAddGift: "Add gift",
    cartAddingGift: "Adding...",
    cartRemoveGiftSelection: "Remove selection",
    cartScaleApplied: "Applied scale",
    cartScaleAvailable: "Available scales",
    cartScaleMax: "You are on the highest wholesale scale for this product.",
    cartScaleNext: "Next scale: {discount}.",
    cartScaleMissing: "Add {count} more piece(s) for {discount}.",
    cartScaleRangeFrom: "From {from} pcs.",
    cartScaleRangeExact: "{from} pcs.",
    cartScaleRangeBetween: "{from} to {to} pcs.",
    cashback: "Cashback",
    cashbackApplied: "Cashback applied",
    cashbackAvailable: "Available cashback",
    cashbackEarn: "Cashback to earn",
    checkoutAcceptTerms: "I accept",
    checkoutAcceptedTermsLink: "terms and conditions",
    checkoutAddressChange: "Change address",
    checkoutAddressConfigure: "Set shipping address",
    checkoutAddressCreated: "Address created successfully.",
    checkoutAddressDefault: "Default",
    checkoutAddressDefaultUse: "Use as default address",
    checkoutAddressDeliveryInstructions: "Delivery instructions",
    checkoutAddressFormAlias: "Alias",
    checkoutAddressFormComplement: "Address line 2",
    checkoutAddressFormContact: "Contact",
    checkoutAddressFormNeighborhood: "Neighborhood",
    checkoutAddressFormPhone: "Phone",
    checkoutAddressFormState: "State",
    checkoutAddressFormStreet: "Street and number",
    checkoutAddressFormZip: "Zip code",
    checkoutAddressPending: "Address pending",
    checkoutAddressReady: "Address ready",
    checkoutAddressSelectedUse: "Use selected address",
    checkoutAddressesAvailable: "Available addresses",
    checkoutAddressesEmpty: "You do not have saved addresses. Add one to continue.",
    checkoutAddressesLoading: "Loading addresses...",
    checkoutAddAddress: "Add address",
    checkoutAddAnotherAddress: "Add another address",
    checkoutAmountDue: "Amount due",
    checkoutBackToCart: "Back to cart",
    checkoutBlockersTitle: "Pending items to complete your order",
    checkoutCustomer: "Customer",
    checkoutCustomerUnknown: "Unidentified customer",
    checkoutDetailTitle: "Product details",
    checkoutDownloadPreview: "Download order preview",
    checkoutEmptyText: "Add products to generate the invoice preview.",
    checkoutGiftAccountingTotal: "Billed gifts",
    checkoutGiftSelectedShort: "Selected",
    checkoutInvoiceEyebrow: "Invoice preview",
    checkoutInvoiceMeta: "Review items, applied promotions and total before continuing.",
    checkoutItemsInDocument: "{count} piece(s) in the document",
    checkoutLoadingText: "We are calculating items, promotions and totals.",
    checkoutLoadingTitle: "Loading invoice preview...",
    checkoutNoAppliedPromotions: "No applied promotions.",
    checkoutNotesPlaceholder: "Write notes for the document or order.",
    checkoutPayStripe: "Pay with Stripe",
    checkoutPaymentRedirecting: "Redirecting...",
    checkoutPaymentValidating: "Validating checkout...",
    checkoutPdfTitle: "Order preview #{id}",
    checkoutPdfValidation: "Order preview for validation",
    checkoutPendingAddressText: "Select or add a shipping address to continue.",
    checkoutProductNumber: "Product #{id}",
    checkoutPromotionsAppliedSubtitle: "Discounts calculated by the promotions engine",
    checkoutSelectedAddressRemove: "Remove selected address",
    checkoutShipping: "Delivery",
    checkoutSystemNotes: "System notes",
    checkoutTitle: "Checkout #{id}",
    checkoutTotalToPay: "Total to pay",
    checkoutDocumentNotes: "Document notes",
    checkoutDocumentNotesText: "Add a brief note for this order",
    checkoutClose: "Close",
    discount: "Discount",
    firstPurchase: "First purchase",
    gift: "Gift",
    giftPending: "{count} gift(s) pending selection",
    giftSelected: "Selected gift",
    loyalty: "Loyalty",
    loyaltyBenefits: "Benefits applied to your account",
    regular: "Regular",
    savings: "Savings",
    shippingAddress: "Shipping address",
    subtotal: "Subtotal",
    tax: "Taxes",
    unitPrice: "Price",
    total: "Total",
    orderSummary: "Order summary",
    continueShopping: "Continue shopping",
    checkoutStockWarning: "Adjust products with insufficient stock before paying.",
    validCashbackAmount: "Enter a valid cashback amount.",
    validCouponCode: "Enter a coupon code.",
    couponAppliedSuccess: "Coupon applied successfully.",
    couponApplyError: "Could not apply the coupon.",
    couponRemovedSuccess: "Coupon removed from cart.",
    couponRemoveError: "Could not remove the coupon.",
    quantityEmpty: "Quantity cannot be empty.",
    quantityInvalid: "Enter a valid quantity.",
    giftSelectionCleared: "Gift selection removed successfully.",
    giftSelectionClearError: "Could not remove the gift selection.",
    checkoutAcceptTermsWarning: "Accept the terms and conditions to continue with payment.",
    checkoutAddressConfigureWarning: "Set a shipping address to continue.",
    checkoutGiftWarning: "Choose your gift before continuing with payment.",
    checkoutCreateOrderError: "Could not create the order to start payment.",
    checkoutStripeUrlError: "Stripe did not return a payment URL.",
    checkoutStripeStartError: "Could not start payment with Stripe.",
    checkoutLoadAddressError: "Could not load your addresses.",
    checkoutRecalculateError: "Could not recalculate checkout with that address.",
    checkoutAddressRequiredFields: "Complete alias, street and zip code.",
    checkoutCreateAddressError: "Could not create the address.",
    checkoutPopupWarning: "Allow pop-ups to generate the PDF preview.",
    checkoutAddressPanelSubtitle: "Select a saved address or add a new one to continue.",
    checkoutNoContact: "No contact",
    checkoutNoPhone: "No phone",
    checkoutDeliveryPlaceholder: "Ring the black doorbell. Deliver at reception.",
    defaultStoreName: "Online store",
    checkoutAdjustCart: "Adjust quantities in cart",
    checkoutPendingGiftText: "You must choose the pending gift before continuing.",
    checkoutStockSummaryWarning: "Some products do not have enough stock. Adjust quantities in cart.",
    checkoutCannotContinue: "Checkout cannot continue right now.",
    checkoutPendingGeneric: "There is a pending item to resolve.",
    checkoutNoAdditionalNotes: "No additional notes.",
    product: "Product",
    quantityShort: "Qty.",
    saving: "Saving...",
    promoBuySkuGift: "Buy SKU and get a gift",
    promoBrandGiftChoice: "Brand amount and choose gift",
    promoBrandGiftProduct: "Brand amount and get SKU",
    promoBuyXGetY: "Buy X and get Y",
    promoBuyXDiscount: "Buy X and get % off",
    promoDirectDiscount: "Direct discount",
    promoStrikethrough: "Strikethrough price",
    promoPriceScale: "Volume scales",
    totals: "Totals",
    accountProfileTitle: "My details",
    accountProfileDescription: "View your email, customer number, company and account security.",
    accountProfileIntro: "Complete your business, tax and delivery profile to keep your account ready.",
    accountProfileLoadError: "Could not load your details.",
    accountAddressesTitle: "My addresses",
    accountAddressesDescription: "Review your saved delivery addresses and see which one is primary.",
    accountAddressesIntro: "Review your delivery addresses and define which one to use as default.",
    accountAddressesLoadingText: "We are loading your saved addresses.",
    accountAddressesEmptyTitle: "No addresses available",
    accountAddressesEmptyText: "Add a delivery address to complete your orders.",
    accountAddressAdded: "Address added successfully.",
    accountAddressUpdated: "Address updated successfully.",
    accountAddressSaveError: "Could not save the address.",
    accountAddressAlreadyDefault: "This is already your default address.",
    accountAddressDefaultUpdated: "Default address updated.",
    accountAddressDefaultError: "Could not update the default address.",
    accountAddressDeleted: "Address deleted successfully.",
    accountAddressDeleteError: "Could not delete the address.",
    accountAddressDeleteConfirm: "Delete address \"{alias}\"?",
    accountSavedAddress: "Saved address",
    accountNoAlias: "No alias",
    accountViewDeliveryInstructions: "View delivery instructions",
    accountMarkAsDefault: "Mark as default",
    accountEditAddress: "Edit address",
    accountAddressModalText: "Complete the delivery details for your account.",
    accountSaveAddress: "Save address",
    accountOrdersDescription: "Review your purchases, payments, products, benefits and order notes.",
    accountOrdersSummary: "Order summary",
    accountOrdersLoadError: "Could not load your orders.",
    accountOrderDetailLoadError: "Could not load the order detail.",
    accountOrderSearchPlaceholder: "Search by order number",
    accountOrdersList: "Order list",
    accountOrdersLoading: "Loading orders...",
    accountOrdersEmpty: "We could not find orders with these filters.",
    accountSelectOrder: "Select an order",
    accountSelectOrderText: "Open it to view products, address, payments, benefits and notes.",
    accountOrderDetailLoading: "Updating detail...",
    accountOrderNoProducts: "This order has no registered products.",
    accountNoAddress: "No registered address",
    all: "All",
    allPayments: "All payments",
    apply: "Apply",
    change: "Change",
    city: "City",
    company: "Company",
    completeAllFields: "Complete all fields",
    confirm: "Confirm",
    currentPassword: "Current password",
    currentPasswordPlaceholder: "Enter your current password",
    customer: "Customer",
    date: "Date",
    edit: "Edit",
    from: "From",
    method: "Method",
    newPassword: "New password",
    newPasswordPlaceholder: "Enter your new password",
    noAttributes: "No attributes",
    noMethod: "No method",
    noPayment: "No payment",
    notRegistered: "Not registered",
    order: "Order",
    orderCancelled: "Cancelled",
    orderDiscount: "Order discount",
    orderNotes: "Order notes",
    orders: "Orders",
    other: "Other",
    paid: "Paid",
    paymentCash: "Cash",
    paymentCashTransfer: "Cash and transfer",
    paymentCheck: "Check",
    paymentFailed: "Failed",
    paymentMethod: "Payment method",
    paymentPaid: "Paid",
    paymentPaidPlural: "Paid",
    paymentPending: "Pending",
    paymentTransfer: "Bank transfer",
    periodTotal: "Period total",
    phoneNumber: "Phone number",
    shipping: "Shipping",
    showingRange: "Showing {from}-{to} of {total}",
    sortLatest: "Newest",
    sortOldest: "Oldest",
    sortPaidRecent: "Recently paid",
    sortTotalAsc: "Lowest total",
    sortTotalDesc: "Highest total",
    to: "To",
    cancel: "Cancel",
    saveProfile: "Save profile",
    saveAndContinue: "Save and continue",
    password: "Password",
    passwordChangePending: "Change pending",
    passwordUpdatedStatus: "Updated",
    passwordMinLength: "The new password must be at least 8 characters.",
    passwordMismatch: "Password confirmation does not match.",
    passwordMustBeDifferent: "The new password must be different from the previous one.",
    passwordUpdating: "Updating password...",
    passwordUpdated: "Password updated successfully.",
    passwordUpdateError: "Could not update the password.",
    changePassword: "Change password",
    changeTemporaryPassword: "Change your temporary password",
    changePasswordText: "Enter your current password and set a new password for your account.",
    confirmPassword: "Confirm password",
    confirmPasswordPlaceholder: "Confirm your new password",
    commercialName: "Business name",
    commercialNameRequired: "Business name is required.",
    purchasingContact: "Purchasing contact",
    quoteEmail: "Quote email",
    businessPhone: "Business phone",
    secondaryContact: "Secondary contact",
    secondaryPhone: "Secondary phone",
    businessActivity: "Business activity",
    requiresInvoice: "Requires invoice",
    fiscalName: "Legal name",
    fiscalStreet: "Tax street",
    externalNumber: "External no.",
    internalNumber: "Internal no.",
    cfdiUse: "CFDI use",
    taxCertificatePdf: "Tax certificate PDF",
    viewCurrentCertificate: "View current certificate",
    deliverySameAsFiscal: "Delivery address is the same as tax address",
    completeFiscalAddress: "Complete the tax address in the previous step.",
    deliverySchedule: "Delivery schedule",
    deliveryObservations: "Delivery observations",
    deliveryAddressRequired: "Enter the delivery address or mark it as same as tax address.",
    distintivoHHelp: "Corresponds to the guarantee seal that a business meets to protect consumer health. Example: NO wet/dirty cardboard boxes; NO dented, swollen or rusty cans.",
    pfrCommercialProfile: "Business profile",
    pfrCommercialShort: "Business",
    pfrCommercialDescription: "Contact details, activity and purchase conditions.",
    pfrFiscalData: "Tax data",
    pfrFiscalShort: "Tax",
    pfrFiscalDescription: "Legal name, RFC, tax address and certificate.",
    pfrDeliveryDescription: "Address, schedules and delivery observations.",
    pfrStepProgress: "Step {current} of {total} · Profile {percent}% complete",
    pendingFields: "Pending fields",
    pfrComplete: "Your PFR profile is complete.",
    pfrPdfRequired: "The certificate must be a PDF file.",
    pfrSaved: "PFR profile saved successfully.",
    pfrSaveError: "Could not save the PFR profile.",
    progressSaved: "Progress saved successfully.",
    reviewMarkedFields: "Review the marked fields before continuing.",
    validCfdiUse: "Select a valid CFDI use.",
    validEmail: "Enter a valid email.",
    validPhone: "Enter a valid 10 to 15 digit phone number.",
    validRfc: "RFC must be alphanumeric and have 13 or 14 characters.",
    validZipCode: "Zip code must have 5 digits.",
    categories: "Categories",
    category: "Category",
    catalogCategories: "Product categories",
    clearFilters: "Clear filters",
    contact: "Contact",
    contactIntro: "Write to us for questions about orders, deliveries, customer registration or supplier information.",
    contactLocation: "Our location",
    contactNamePlaceholder: "John Doe",
    currentPromotion: "Active promotion",
    currentPromotions: "active promotion(s)",
    currency: "Currency",
    dailyOffer: "Deal of the day",
    details: "Details",
    emptyRecentProducts: "We could not find recent products right now.",
    favorites: "Favorites",
    filters: "Filters",
    higherPrice: "Highest price",
    home: "Home",
    inStock: "In stock",
    inactive: "Inactive",
    keyword: "Keyword",
    interestedProducts: "You may also like",
    language: "Language",
    loadingCategories: "Loading categories...",
    loading: "Loading...",
    name: "Name",
    nameRequired: "Name required",
    email: "Email",
    emailRequired: "Email required",
    newsletterTitle: "Register",
    newsletterShortText: "Join our community, leave us your details.",
    newsletterText: "Receive promotions, news and exclusive benefits directly in your email.",
    privacyNotice: "Privacy notice",
    terms: "Terms and conditions",
    send: "Send",
    sendMessage: "Send message",
    sending: "Sending...",
    description: "Description",
    productDescription: "Product description",
    discountSuffix: "discount",
    fromPieces: "From {from} pieces",
    pieces: "{count} pieces",
    piecesRange: "From {from} to {to} pieces",
    technicalSheet: "Technical sheet",
    yes: "Yes",
    no: "No",
    messageRequired: "Message required",
    faqs: "Frequently asked questions",
    family: "Family",
    legal: "Legal",
    socialNetworks: "Our social networks",
    login: "Sign in",
    loginToBuy: "Sign in to buy",
    loginToSeePrices: "Sign in to see prices",
    lowStock: "Only a few pieces left.",
    lowerPrice: "Lowest price",
    logout: "Sign out",
    mostRelevant: "Most relevant",
    monthlyPromotions: "Monthly promotions",
    monthlyPromotionsSubtitle: "Take advantage of active promotions selected for your business.",
    myAccount: "My account",
    noCategories: "No categories available",
    noProductsFound: "We could not find products for this search.",
    noOfferAvailable: "No offer available.",
    noBaseSku: "No base SKU",
    noStock: "No stock",
    notAvailable: "N/A",
    next: "Next",
    previous: "Previous",
    previousImage: "Previous image",
    add: "Add",
    choosePromotionProduct: "Choose a product from this promotion to add it to the cart.",
    results: "results",
    resultsFor: "Results for \"{term}\"",
    sortBy: "Sort by",
    mostPopular: "Most popular",
    priceLowToHigh: "Price: low to high",
    priceHighToLow: "Price: high to low",
    nameAsc: "Name A-Z",
    nameDesc: "Name Z-A",
    outOfStock: "Out of stock",
    offers: "Offers",
    previousOffers: "View previous offers",
    seeProducts: "View products",
    showAllOffers: "Show all offers",
    view: "View",
    viewFullCollection: "View full collection",
    viewMore: "View more",
    viewOffer: "View offer",
    viewFullImage: "View full image",
    previousProducts: "View previous products",
    popularSearches: "Popular searches:",
    popularSearchesRecommended: "Recommended items based on your popular searches",
    priceUnavailable: "Price unavailable",
    productWithoutName: "Unnamed product",
    productLoading: "Loading product...",
    productNotFound: "Product not found",
    productNotFoundText: "The product you are trying to view does not exist or is no longer available.",
    productPromotions: "Product promotions",
    personalProductsSubtitle: "Find inspiration with this selection of items chosen especially for you.",
    products: "Products",
    purchaseInformation: "Purchase information",
    quantity: "Quantity",
    itemsCount: "{count} items",
    recentPurchases: "Products just for you",
    register: "Register",
    regions: "Regions",
    noRegions: "No regions available",
    memberZone: "Member Zone",
    regionMemberText: "Unlock special recommendations and exclusive promotions for members.",
    regionNotFound: "Region not found",
    createAccount: "Create an account",
    removeFavorite: "Remove from favorites",
    removedFromFavorites: "Product removed from favorites.",
    search: "Search",
    searchEmpty: "No matches found.",
    searchFamilies: "Families",
    searchBrands: "Brands",
    searchCategories: "Categories",
    searchLoading: "Searching...",
    searchPlaceholder: "Search in {brandName}",
    searchProducts: "Products",
    searchSuggestion: "Did you mean:",
    selectAttributes: "Select attributes",
    selectAttributesBeforeCart: "Select product attributes before adding it to the cart.",
    selectOption: "Choose",
    share: "Share",
    stock: "Stock",
    status: "Status",
    stockAvailableCount: "{count} available",
    onlyAvailableCount: "Only {count} piece(s) available.",
    wholesaleScales: "Wholesale scales",
    wishlists: "Lists",
    myOrders: "My orders",
    addressAliasBranchPlaceholder: "E.g. Downtown branch",
    addressAliasHomePlaceholder: "Home",
    addressComplementPlaceholder: "Apt. 4B, blue building",
    addressContactPlaceholder: "Receiver name",
    addressNeighborhoodGenericPlaceholder: "Neighborhood",
    addressNeighborhoodPlaceholder: "Downtown",
    addressStateGenericPlaceholder: "State",
    addressStatePlaceholder: "Jalisco",
    addressStreetPlaceholder: "Main Ave. 123",
    backHome: "Back home",
    backToCart: "Back to cart",
    backToLogin: "Back to sign in",
    businessPersonAlt: "Person smiling in their business",
    cartExcelAllowedFormats: "Allowed formats: `.xlsx` and `.xls`. Use the downloaded layout.",
    cartExcelDownloadStep: "1. Download layout",
    cartExcelEditableSheetHelp: "Fill in only `sku` and `quantity`.",
    cartExcelEyebrow: "Cart by Excel",
    cartExcelImportInfoAdd: "They are added to the current cart.",
    cartExcelImportInfoGroup: "Repeated SKUs are grouped and summed.",
    cartExcelImportInfoRead: "The `CargaCarrito` sheet is read.",
    cartExcelImportInfoRecalculate: "Promotions and totals are recalculated at the end.",
    cartExcelImportInfoTitle: "What happens when importing",
    cartExcelLayoutDownloadError: "Could not download the Excel layout.",
    cartExcelLayoutDownloaded: "Layout downloaded successfully.",
    cartExcelLayoutIncludesEnd: "sheet for reference.",
    cartExcelLayoutIncludesMiddle: "and an ",
    cartExcelLayoutIncludesStart: "The file includes the ",
    cartExcelPreparing: "We are preparing the Excel cart upload.",
    cartExcelProcessError: "Could not process the Excel file.",
    cartExcelProcessed: "Excel file processed successfully.",
    cartExcelSelectFile: "Select your Excel file",
    cartExcelSelectFileWarning: "Select an Excel file to process.",
    cartExcelSubtitleEnd: "and upload the file to update your current cart.",
    cartExcelSubtitleStart: "Download the layout, fill out the",
    cartExcelSummaryTitle: "Process summary",
    cartExcelSupportSheetHelp: "Check SKUs, brands and current prices.",
    cartExcelTitle: "Bulk order upload",
    cartExcelUploadStep: "2. Upload file",
    cartExcelUploadText: "We process repeated SKUs, add quantities and update the cart with recalculated promotions.",
    cartItems: "Cart items",
    cartRecoveredTitle: "Cart recovered",
    cartRecoverError: "Could not recover the cart.",
    cartRecovering: "Recovering cart...",
    checkConditionsAtPurchase: "Check conditions when purchasing.",
    checkoutConfirmingPayment: "Confirming your payment",
    checkoutConfirmingStripe: "Confirming payment with Stripe...",
    checkoutLoadingOrder: "Loading order...",
    checkoutOrderDetailUnavailable: "Could not load the detail right now.",
    checkoutOrderLoadError: "Could not load the order.",
    checkoutPaymentCanceled: "Payment canceled",
    checkoutPaymentConfirmed: "Payment confirmed successfully.",
    checkoutPaymentConfirmingWarning: "Payment is being confirmed. Check the order status in a few moments.",
    checkoutPaymentInProgress: "Payment in progress",
    checkoutPaymentNotCompleted: "Payment was not completed",
    checkoutPaymentReceived: "Payment received",
    checkoutRecoveredProductsReady: "{count} product(s) ready to continue.",
    checkoutRecoveringCartText: "We are recovering your cart so you can review it or try the payment again.",
    checkoutStripeValidationText: "We validate the Stripe session and keep the webhook as a confirmation backup.",
    closeFullView: "Close full view",
    confirmPassword: "Confirm password",
    create: "Create",
    creating: "Creating...",
    deleteList: "Delete list",
    deliveryAvailable: "Delivery available",
    downloadLayout: "Download layout",
    downloading: "Downloading...",
    editableSheet: "Editable sheet",
    editGoogleMapsLink: "Edit Google Maps link",
    emailInvalid: "Enter a valid email.",
    emailPlaceholder: "customer@email.com",
    favoritesEmptyText: "Save products from the catalog or from each product detail page.",
    favoritesEmptyTitle: "You do not have favorites yet",
    favoritesLoadError: "Could not load your favorites.",
    forgotPasswordError: "Could not request password recovery.",
    forgotPasswordRemembered: "Remembered your password?",
    forgotPasswordSuccess: "If the email exists, we will send instructions to recover your password.",
    forgotPasswordTitle: "Recover access to your account",
    goHome: "Go home",
    goToMyAccount: "Go to my account",
    highTurnover: "High turnover",
    importedItems: "Imported items",
    importedRows: "Imported rows",
    loginNavigation: "Sign in navigation",
    loginNoAccount: "Do not have an account?",
    loginPageTitle: "Sign in and continue shopping for your business",
    loginRecoverCartNotice: "Sign in to recover your cart.",
    loginRecoverCartText: "After signing in, we will activate your abandoned cart and take you back to checkout.",
    loginRecoverCartTitle: "Sign in to recover your cart",
    loadingLists: "Loading lists...",
    newList: "New list",
    newProducts: "New Products",
    newPassword: "New password",
    nextImage: "Next image",
    nextProducts: "View next products",
    noBrand: "No brand",
    noSku: "No SKU",
    notFoundText: "The page you are looking for does not exist.",
    passwordMinLength: "It must have at least 8 characters.",
    passwordMinPlaceholder: "Minimum 8 characters",
    passwordRequired: "Password is required.",
    passwordUpdateError: "Could not update the password.",
    passwordUpdated: "Password updated successfully.",
    passwordsDoNotMatch: "Passwords do not match.",
    payment: "Payment",
    processCart: "Process cart",
    processedRows: "Processed rows",
    processing: "Processing...",
    productsCount: "{count} product(s)",
    recoveryNavigation: "Recovery navigation",
    registerNavigation: "Registration navigation",
    registerPageTitle: "Create your account and buy faster for your business",
    removeFromList: "Remove from list",
    removeFile: "Remove file",
    repeatPasswordPlaceholder: "Repeat your password",
    rejectedRows: "Rejected rows",
    resetLinkInvalid: "The recovery link is not valid.",
    resetLinkMissingEmail: "The link does not include a valid email.",
    resetNavigation: "Password reset navigation",
    resetPasswordIntro: "Then you can",
    resetPasswordIntroSuffix: "with your new credentials.",
    resetPasswordTitle: "Create a new password",
    savedListsCount: "{count} saved list(s)",
    savedProductsCount: "{count} saved product(s)",
    row: "Row",
    rowImportError: "Could not import the row.",
    rows: "Rows",
    searchInterpretation: "Search interpretation",
    sendInstructions: "Send instructions",
    secureCheckout: "Secure and protected checkout",
    shippingAndReturns: "Shipping and returns",
    shippingByCoverage: "Shipping according to coverage.",
    shopCollection: "Shop the collection",
    signUp: "Sign up",
    skippedRows: "Skipped rows",
    supportSheet: "Support sheet",
    tryAgain: "Try again",
    unnamedProduct: "Unnamed product",
    updatePassword: "Update password",
    viewUpdatedCart: "View updated cart",
    wishlistCreateError: "Could not create the list.",
    wishlistCreated: "List created successfully.",
    wishlistDeleteConfirm: "Delete this list?",
    wishlistDeleteError: "Could not delete the list.",
    wishlistDeleted: "List deleted successfully.",
    wishlistEmptyText: "Add products from the catalog or product detail page.",
    wishlistEmptyTitle: "Empty list",
    wishlistProductRemoveError: "Could not remove the product.",
    wishlistProductRemoved: "Product removed from the list.",
    wishlistProductsLoadError: "Could not load the products in this list.",
    wishlistsEmptyShort: "You do not have lists yet.",
    wishlistsEmptyText: "Create a list to save products by occasion or frequent purchase.",
    wishlistsEmptyTitle: "You do not have lists yet",
    wishlistsLoadError: "Could not load your lists.",
  },
  es: {
    addToCart: "Agregar al carrito",
    addingToCart: "Agregando...",
    addToWishlist: "Agregar a lista",
    askQuestion: "Hacer una pregunta",
    attributes: "Atributos",
    automaticInCart: "Automático en carrito",
    active: "Activo",
    activePromotions: "Promociones activas",
    appliesPromotions: "Aplica promociones",
    artisanSelectionTitle: "Selección de nuestros artesanos",
    addedToCart: "Producto agregado al carrito.",
    addedToFavorites: "Producto agregado a favoritos.",
    addFavorite: "Agregar a favoritos",
    baseSku: "SKU base",
    brand: "Marca",
    brands: "Marcas",
    cart: "Carrito",
    cartAddedProductsMeta: "{products} productos · {pieces} piezas",
    cartAppliedPromotion: "Promo aplicada",
    cartAvailable: "Disponible",
    cartClear: "Vaciar carrito",
    cartClearing: "Vaciando...",
    cartContinueCheckout: "Continuar al checkout",
    cartEmptyText: "Aún no tienes productos agregados. Explora el catálogo y comienza tu pedido.",
    cartEmptyTitle: "Tu carrito está vacío",
    cartGiftPending: "{count} regalo(s) pendiente(s) por elegir",
    cartGiftSelected: "Regalo elegido",
    cartGoToProducts: "Ir a productos",
    cartInsufficientStock: "Inventario insuficiente",
    cartLoadingText: "Espera un momento mientras obtenemos tus productos.",
    cartLoadingTitle: "Cargando carrito...",
    cartNoProductsFound: "No encontramos productos en tu carrito",
    cartNoProductsFoundText: "Prueba con otro término o ajusta tu búsqueda.",
    cartProcessOrder: "Procesar pedido",
    cartQuickWholesaleOrder: "Pedido rápido de mayoreo",
    cartRegionalSplitsTitle: "Distribución regional",
    cartRegionalSplitsText: "División estimada por centro regional.",
    cartRegionalSource: "Centro regional: {region}",
    commissionEstimated: "Comisión estimada",
    netEstimated: "Neto estimado",
    cartRemove: "Eliminar",
    cartRemoveSelection: "Eliminar seleccionados",
    cartRemoving: "Eliminando...",
    cartReviewAvailability: "Revisar disponibilidad",
    cartSaveList: "Guardar en lista",
    cartSearchPlaceholder: "Buscar dentro del carrito",
    cartSelectProduct: "Seleccionar {name}",
    cartShowingProducts: "Mostrando {shown} de {total} productos",
    cartUnitPrice: "P. Unitario",
    cartClearSuccess: "Carrito vaciado correctamente.",
    cartCouponApplied: "Cupón aplicado al carrito",
    cartCouponCodePrompt: "Agrega un código promocional",
    cartCouponTitle: "Cupón",
    cartInvalidCoupon: "No válido",
    cartApplyCoupon: "Aplicar",
    cartApplying: "Aplicando...",
    cartRemoveCoupon: "Quitar",
    cartRemovingSelection: "Quitando...",
    cartRecovered: "Carrito recuperado correctamente.",
    cartRemoveProductError: "No fue posible eliminar el producto.",
    cartRemoveSelectedSuccess: "Productos seleccionados eliminados correctamente.",
    cartRemoveSelectedError: "No fue posible eliminar los productos seleccionados.",
    cartSelectAtLeastOne: "Selecciona al menos un producto.",
    cartGiftChosen: "Regalo seleccionado correctamente.",
    cartGiftChoosePending: "Selecciona tu regalo pendiente antes de continuar al checkout.",
    cartGiftAccounting: "{units} regalo(s) facturado(s) a {unitPrice} c/u ({lineTotal})",
    cartGiftItems: "{units} regalo(s) de artículos promocionales{names}",
    cartGiftAvailable: "Regalo disponible",
    cartChooseGift: "Elige tu regalo para completar esta promoción.",
    cartSelectedGiftLabel: "Regalo seleccionado",
    cartGiftSku: "SKU regalo #{sku} · Cantidad {quantity}",
    cartGiftSkuAdded: "El SKU regalo ya está en tu carrito.",
    cartAddGift: "Agregar regalo",
    cartAddingGift: "Agregando...",
    cartRemoveGiftSelection: "Quitar selección",
    cartScaleApplied: "Escala aplicada",
    cartScaleAvailable: "Escalas disponibles",
    cartScaleMax: "Estás en la escala máxima de mayoreo para este producto.",
    cartScaleNext: "Siguiente escala: {discount}.",
    cartScaleMissing: "Agrega {count} pza(s) más para {discount}.",
    cartScaleRangeFrom: "Desde {from} pzas.",
    cartScaleRangeExact: "{from} pzas.",
    cartScaleRangeBetween: "{from} a {to} pzas.",
    cashback: "Cashback",
    cashbackApplied: "Cashback aplicado",
    cashbackAvailable: "Cashback disponible",
    cashbackEarn: "Cashback a ganar",
    checkoutAcceptTerms: "Acepto",
    checkoutAcceptedTermsLink: "términos y condiciones",
    checkoutAddressChange: "Cambiar dirección",
    checkoutAddressConfigure: "Configurar dirección de envío",
    checkoutAddressCreated: "Dirección creada correctamente.",
    checkoutAddressDefault: "Predeterminada",
    checkoutAddressDefaultUse: "Usar como dirección predeterminada",
    checkoutAddressDeliveryInstructions: "Instrucciones de entrega",
    checkoutAddressFormAlias: "Alias",
    checkoutAddressFormComplement: "Complemento",
    checkoutAddressFormContact: "Contacto",
    checkoutAddressFormNeighborhood: "Colonia",
    checkoutAddressFormPhone: "Teléfono",
    checkoutAddressFormState: "Estado",
    checkoutAddressFormStreet: "Calle y número",
    checkoutAddressFormZip: "Código postal",
    checkoutAddressPending: "Dirección pendiente",
    checkoutAddressReady: "Dirección lista",
    checkoutAddressSelectedUse: "Usar dirección seleccionada",
    checkoutAddressesAvailable: "Direcciones disponibles",
    checkoutAddressesEmpty: "No tienes direcciones guardadas. Agrega una para poder continuar.",
    checkoutAddressesLoading: "Cargando direcciones...",
    checkoutAddAddress: "Agregar dirección",
    checkoutAddAnotherAddress: "Agregar otra dirección",
    checkoutAmountDue: "Importe a pagar",
    checkoutBackToCart: "Volver al carrito",
    checkoutBlockersTitle: "Pendientes para completar tu pedido",
    checkoutCustomer: "Cliente",
    checkoutCustomerUnknown: "Cliente no identificado",
    checkoutDetailTitle: "Detalle de productos",
    checkoutDownloadPreview: "Descargar previa de pedido",
    checkoutEmptyText: "Agrega productos para generar la previa de factura.",
    checkoutGiftAccountingTotal: "Regalos facturados",
    checkoutGiftSelectedShort: "Elegido",
    checkoutInvoiceEyebrow: "Previa de factura",
    checkoutInvoiceMeta: "Revisa partidas, promociones aplicadas y total antes de continuar.",
    checkoutItemsInDocument: "{count} pieza(s) en el documento",
    checkoutLoadingText: "Estamos calculando partidas, promociones y totales.",
    checkoutLoadingTitle: "Cargando previa de factura...",
    checkoutNoAppliedPromotions: "No hay promociones aplicadas.",
    checkoutNotesPlaceholder: "Escribe notas para el documento o pedido.",
    checkoutPayStripe: "Pagar con Stripe",
    checkoutPaymentRedirecting: "Redirigiendo...",
    checkoutPaymentValidating: "Validando checkout...",
    checkoutPdfTitle: "Previa de pedido #{id}",
    checkoutPdfValidation: "Previa de pedido para validación",
    checkoutPendingAddressText: "Selecciona o agrega una dirección de envío para poder continuar.",
    checkoutProductNumber: "Producto #{id}",
    checkoutPromotionsAppliedSubtitle: "Descuentos calculados por el motor de promociones",
    checkoutSelectedAddressRemove: "Quitar dirección seleccionada",
    checkoutShipping: "Entrega",
    checkoutSystemNotes: "Notas del sistema",
    checkoutTitle: "Checkout #{id}",
    checkoutTotalToPay: "Total a pagar",
    checkoutDocumentNotes: "Notas del documento",
    checkoutDocumentNotesText: "Agrega una nota breve para este pedido",
    checkoutClose: "Cerrar",
    discount: "Descuento",
    firstPurchase: "Primera compra",
    gift: "Regalo",
    giftPending: "{count} regalo(s) pendiente(s) por elegir",
    giftSelected: "Regalo elegido",
    loyalty: "Fidelidad",
    loyaltyBenefits: "Beneficios aplicados a tu cuenta",
    regular: "Regular",
    savings: "Ahorro",
    shippingAddress: "Dirección de envío",
    subtotal: "Subtotal",
    tax: "Impuestos",
    unitPrice: "Precio",
    total: "Total",
    orderSummary: "Resumen de compra",
    continueShopping: "Seguir comprando",
    checkoutStockWarning: "Ajusta los productos sin inventario suficiente antes de pagar.",
    validCashbackAmount: "Ingresa un monto de cashback válido.",
    validCouponCode: "Ingresa un código de cupón.",
    couponAppliedSuccess: "Cupón aplicado correctamente.",
    couponApplyError: "No fue posible aplicar el cupón.",
    couponRemovedSuccess: "Cupón eliminado del carrito.",
    couponRemoveError: "No fue posible quitar el cupón.",
    quantityEmpty: "La cantidad no puede quedar vacía.",
    quantityInvalid: "Ingresa una cantidad válida.",
    giftSelectionCleared: "Selección de regalo eliminada correctamente.",
    giftSelectionClearError: "No fue posible eliminar la selección del regalo.",
    checkoutAcceptTermsWarning: "Acepta los términos y condiciones para continuar con el pago.",
    checkoutAddressConfigureWarning: "Configura una dirección de envío para continuar.",
    checkoutGiftWarning: "Debes elegir tu regalo antes de continuar con el pago.",
    checkoutCreateOrderError: "No fue posible crear el pedido para iniciar el pago.",
    checkoutStripeUrlError: "Stripe no devolvió una URL de pago.",
    checkoutStripeStartError: "No fue posible iniciar el pago con Stripe.",
    checkoutLoadAddressError: "No fue posible cargar tus direcciones.",
    checkoutRecalculateError: "No fue posible recalcular el checkout con esa dirección.",
    checkoutAddressRequiredFields: "Completa alias, calle y código postal.",
    checkoutCreateAddressError: "No fue posible crear la dirección.",
    checkoutPopupWarning: "Permite ventanas emergentes para generar la previa en PDF.",
    checkoutAddressPanelSubtitle: "Selecciona una dirección guardada o agrega una nueva para continuar.",
    checkoutNoContact: "Sin contacto",
    checkoutNoPhone: "Sin teléfono",
    checkoutDeliveryPlaceholder: "Tocar el timbre negro. Entregar en recepción.",
    defaultStoreName: "Tienda en línea",
    checkoutAdjustCart: "Ajustar cantidades en carrito",
    checkoutPendingGiftText: "Debes elegir el regalo pendiente para poder continuar.",
    checkoutStockSummaryWarning: "Hay productos sin inventario suficiente. Ajusta cantidades en carrito.",
    checkoutCannotContinue: "El checkout no puede continuar por el momento.",
    checkoutPendingGeneric: "Hay un pendiente por resolver.",
    checkoutNoAdditionalNotes: "Sin notas adicionales.",
    product: "Producto",
    quantityShort: "Cant.",
    saving: "Guardando...",
    promoBuySkuGift: "Compra SKU y recibe regalo",
    promoBrandGiftChoice: "Monto por marca y elige regalo",
    promoBrandGiftProduct: "Monto por marca y recibe SKU",
    promoBuyXGetY: "Compra X y llévate Y",
    promoBuyXDiscount: "Compra X y obtén % OFF",
    promoDirectDiscount: "Descuento directo",
    promoStrikethrough: "Precio tachado",
    promoPriceScale: "Escalas por volumen",
    totals: "Totales",
    accountProfileTitle: "Mis datos",
    accountProfileDescription: "Consulta tu correo, número de cliente, empresa y administra la seguridad de tu cuenta.",
    accountProfileIntro: "Completa tu perfil comercial, fiscal y de entrega para dejar lista tu cuenta.",
    accountProfileLoadError: "No fue posible cargar tus datos.",
    accountAddressesTitle: "Mis direcciones",
    accountAddressesDescription: "Revisa las direcciones registradas para entrega y consulta cuál tienes como principal.",
    accountAddressesIntro: "Consulta tus domicilios de entrega y define cuál usar como predeterminada.",
    accountAddressesLoadingText: "Estamos obteniendo tus domicilios guardados.",
    accountAddressesEmptyTitle: "No hay direcciones disponibles",
    accountAddressesEmptyText: "Agrega una dirección de entrega para poder completar tus pedidos.",
    accountAddressAdded: "Dirección agregada correctamente.",
    accountAddressUpdated: "Dirección actualizada correctamente.",
    accountAddressSaveError: "No fue posible guardar la dirección.",
    accountAddressAlreadyDefault: "Esta ya es tu dirección predeterminada.",
    accountAddressDefaultUpdated: "Dirección predeterminada actualizada.",
    accountAddressDefaultError: "No fue posible actualizar la predeterminada.",
    accountAddressDeleted: "Dirección eliminada correctamente.",
    accountAddressDeleteError: "No fue posible eliminar la dirección.",
    accountAddressDeleteConfirm: "¿Eliminar la dirección \"{alias}\"?",
    accountSavedAddress: "Dirección guardada",
    accountNoAlias: "Sin alias",
    accountViewDeliveryInstructions: "Ver instrucciones de entrega",
    accountMarkAsDefault: "Marcar como predeterminada",
    accountEditAddress: "Editar dirección",
    accountAddressModalText: "Completa los datos de entrega para tu cuenta.",
    accountSaveAddress: "Guardar dirección",
    accountOrdersDescription: "Consulta tus compras, pagos, productos, beneficios y notas del pedido.",
    accountOrdersSummary: "Resumen de pedidos",
    accountOrdersLoadError: "No fue posible cargar tus pedidos.",
    accountOrderDetailLoadError: "No fue posible cargar el detalle del pedido.",
    accountOrderSearchPlaceholder: "Buscar por número de pedido",
    accountOrdersList: "Listado de pedidos",
    accountOrdersLoading: "Cargando pedidos...",
    accountOrdersEmpty: "No encontramos pedidos con estos filtros.",
    accountSelectOrder: "Selecciona un pedido",
    accountSelectOrderText: "Al abrirlo verás productos, dirección, pagos, beneficios y notas.",
    accountOrderDetailLoading: "Actualizando detalle...",
    accountOrderNoProducts: "Este pedido no tiene productos registrados.",
    accountNoAddress: "Sin dirección registrada",
    all: "Todos",
    allPayments: "Todos los pagos",
    apply: "Aplicar",
    change: "Cambiar",
    city: "Ciudad",
    company: "Empresa",
    completeAllFields: "Completa todos los campos",
    confirm: "Confirmar",
    currentPassword: "Contraseña actual",
    currentPasswordPlaceholder: "Ingresa tu contraseña actual",
    customer: "Cliente",
    date: "Fecha",
    edit: "Editar",
    from: "Desde",
    method: "Método",
    newPassword: "Nueva contraseña",
    newPasswordPlaceholder: "Ingresa tu nueva contraseña",
    noAttributes: "Sin atributos",
    noMethod: "Sin método",
    noPayment: "Sin pago",
    notRegistered: "No registrado",
    order: "Pedido",
    orderCancelled: "Cancelado",
    orderDiscount: "Descuento pedido",
    orderNotes: "Notas del pedido",
    orders: "Pedidos",
    other: "Otro",
    paid: "Pagado",
    paymentCash: "Efectivo",
    paymentCashTransfer: "Efectivo y transferencia",
    paymentCheck: "Cheque",
    paymentFailed: "Fallido",
    paymentMethod: "Método de pago",
    paymentPaid: "Pagado",
    paymentPaidPlural: "Pagados",
    paymentPending: "Pendiente",
    paymentTransfer: "Transferencia electrónica",
    periodTotal: "Total del periodo",
    phoneNumber: "Número de teléfono",
    shipping: "Envío",
    showingRange: "Mostrando {from}-{to} de {total}",
    sortLatest: "Más recientes",
    sortOldest: "Más antiguos",
    sortPaidRecent: "Pagados recientes",
    sortTotalAsc: "Total menor",
    sortTotalDesc: "Total mayor",
    to: "Hasta",
    cancel: "Cancelar",
    saveProfile: "Guardar perfil",
    saveAndContinue: "Guardar y seguir",
    password: "Contraseña",
    passwordChangePending: "Cambio pendiente",
    passwordUpdatedStatus: "Actualizada",
    passwordMinLength: "La nueva contraseña debe tener al menos 8 caracteres.",
    passwordMismatch: "La confirmación de contraseña no coincide.",
    passwordMustBeDifferent: "La nueva contraseña debe ser diferente a la anterior.",
    passwordUpdating: "Actualizando contraseña...",
    passwordUpdated: "Contraseña actualizada correctamente.",
    passwordUpdateError: "No se pudo actualizar la contraseña.",
    changePassword: "Cambiar contraseña",
    changeTemporaryPassword: "Cambia tu contraseña temporal",
    changePasswordText: "Ingresa tu contraseña actual y define una nueva contraseña para tu cuenta.",
    confirmPassword: "Confirmar contraseña",
    confirmPasswordPlaceholder: "Confirma tu nueva contraseña",
    commercialName: "Nombre comercial",
    commercialNameRequired: "El nombre comercial es obligatorio.",
    purchasingContact: "Contacto de compras",
    quoteEmail: "Correo para cotizaciones",
    businessPhone: "Teléfono del negocio",
    secondaryContact: "Contacto secundario",
    secondaryPhone: "Teléfono secundario",
    businessActivity: "Giro o actividad",
    requiresInvoice: "Requiere factura",
    fiscalName: "Razón social",
    fiscalStreet: "Calle fiscal",
    externalNumber: "No. exterior",
    internalNumber: "No. interior",
    cfdiUse: "Uso CFDI",
    taxCertificatePdf: "Constancia fiscal PDF",
    viewCurrentCertificate: "Ver constancia actual",
    deliverySameAsFiscal: "La dirección de entrega es igual a la fiscal",
    completeFiscalAddress: "Completa el domicilio fiscal en el paso anterior.",
    deliverySchedule: "Horario de entrega",
    deliveryObservations: "Observaciones de entrega",
    deliveryAddressRequired: "Ingresa la dirección de entrega o marca que es igual a la fiscal.",
    distintivoHHelp: "Corresponde al sello de garantía que un establecimiento cumple, para proteger la salud del consumidor. Ejemplo: NO Cajas de Cartón Húmedas/Sucias; NO latas abolladas, hinchadas u oxidadas.",
    pfrCommercialProfile: "Perfil comercial",
    pfrCommercialShort: "Comercial",
    pfrCommercialDescription: "Datos de contacto, actividad y condiciones de compra.",
    pfrFiscalData: "Datos fiscales",
    pfrFiscalShort: "Fiscal",
    pfrFiscalDescription: "Razón social, RFC, domicilio fiscal y constancia.",
    pfrDeliveryDescription: "Domicilio, horarios y observaciones para reparto.",
    pfrStepProgress: "Paso {current} de {total} · Perfil {percent}% completo",
    pendingFields: "Campos pendientes",
    pfrComplete: "Tu perfil PFR está completo.",
    pfrPdfRequired: "La constancia debe ser un archivo PDF.",
    pfrSaved: "Perfil PFR guardado correctamente.",
    pfrSaveError: "No fue posible guardar el perfil PFR.",
    progressSaved: "Avance guardado correctamente.",
    reviewMarkedFields: "Revisa los campos marcados antes de continuar.",
    validCfdiUse: "Selecciona un uso CFDI válido.",
    validEmail: "Ingresa un correo válido.",
    validPhone: "Ingresa un teléfono válido de 10 a 15 dígitos.",
    validRfc: "El RFC debe ser alfanumérico y tener 13 o 14 caracteres.",
    validZipCode: "El código postal debe tener 5 dígitos.",
    categories: "Categorías",
    category: "Categoría",
    catalogCategories: "Categorías de productos",
    clearFilters: "Limpiar filtros",
    contact: "Contacto",
    contactIntro: "Escríbenos para resolver dudas sobre pedidos, entregas, registro de clientes o información para proveedores.",
    contactLocation: "Nuestra ubicación",
    contactNamePlaceholder: "Juan Pérez",
    currentPromotion: "Promoción vigente",
    currentPromotions: "promoción(es) vigente(s)",
    currency: "Moneda",
    dailyOffer: "Oferta del día",
    details: "Detalles",
    emptyRecentProducts: "No encontramos productos recientes por el momento.",
    favorites: "Favoritos",
    filters: "Filtros",
    higherPrice: "Mayor precio",
    home: "Inicio",
    inStock: "Inventario disponible",
    inactive: "Inactivo",
    keyword: "Keyword",
    interestedProducts: "Te puede interesar",
    language: "Idioma",
    loadingCategories: "Cargando categorías...",
    loading: "Cargando...",
    name: "Nombre",
    nameRequired: "Nombre requerido",
    email: "Email",
    emailRequired: "Email requerido",
    newsletterTitle: "Regístrate",
    newsletterShortText: "Quieres ser parte de nuestra comunidad, déjanos tus datos.",
    newsletterText: "Recibe promociones, novedades y beneficios exclusivos directamente en tu correo.",
    privacyNotice: "Aviso de privacidad",
    terms: "Términos y condiciones",
    send: "Enviar",
    sendMessage: "Enviar mensaje",
    sending: "Enviando...",
    description: "Descripción",
    productDescription: "Descripción del producto",
    discountSuffix: "de descuento",
    fromPieces: "Desde {from} piezas",
    pieces: "{count} piezas",
    piecesRange: "De {from} a {to} piezas",
    technicalSheet: "Ficha técnica",
    yes: "Sí",
    no: "No",
    messageRequired: "Mensaje requerido",
    faqs: "Preguntas frecuentes",
    family: "Familia",
    legal: "Legal",
    socialNetworks: "Nuestras redes",
    login: "Iniciar sesión",
    loginToBuy: "Inicia sesión para comprar",
    loginToSeePrices: "Inicia sesión para ver precios",
    lowStock: "Hay pocas piezas disponibles.",
    lowerPrice: "Menor precio",
    logout: "Cerrar sesión",
    mostRelevant: "Más relevantes",
    monthlyPromotions: "Promociones del mes",
    monthlyPromotionsSubtitle: "Aprovecha promociones vigentes seleccionadas para tu negocio.",
    myAccount: "Mi cuenta",
    noCategories: "Sin categorías disponibles",
    noProductsFound: "No encontramos productos para esta búsqueda.",
    noOfferAvailable: "Sin oferta disponible.",
    noBaseSku: "Sin SKU base",
    noStock: "Sin stock",
    notAvailable: "N/D",
    next: "Siguiente",
    previous: "Anterior",
    previousImage: "Imagen anterior",
    add: "Agregar",
    choosePromotionProduct: "Elige un producto de esta promoción para agregarlo al carrito.",
    results: "resultados",
    resultsFor: "Resultados para \"{term}\"",
    sortBy: "Ordenar por",
    mostPopular: "Más popular",
    priceLowToHigh: "Precio: menor a mayor",
    priceHighToLow: "Precio: mayor a menor",
    nameAsc: "Nombre A-Z",
    nameDesc: "Nombre Z-A",
    outOfStock: "Producto sin inventario",
    offers: "Ofertas",
    previousOffers: "Ver ofertas anteriores",
    seeProducts: "Ver productos",
    showAllOffers: "Mostrar todas las ofertas",
    view: "Ver",
    viewFullCollection: "Ver colección completa",
    viewMore: "Ver más",
    viewOffer: "Ver promoción",
    viewFullImage: "Ver imagen completa",
    previousProducts: "Ver productos anteriores",
    popularSearches: "Búsquedas populares:",
    popularSearchesRecommended: "Artículos recomendados basados en tus búsquedas populares",
    priceUnavailable: "Precio no disponible",
    productWithoutName: "Producto sin nombre",
    productLoading: "Cargando producto...",
    productNotFound: "Producto no encontrado",
    productNotFoundText: "El producto que intentas ver no existe o ya no está disponible.",
    productPromotions: "Promociones del producto",
    personalProductsSubtitle: "Encuentra inspiración con esta selección de artículos elegidos especialmente para ti.",
    products: "Productos",
    purchaseInformation: "Información de compra",
    products: "Productos",
    quantity: "Cantidad",
    itemsCount: "{count} elementos",
    recentPurchases: "Productos solo para ti",
    register: "Registrarse",
    regions: "Regiones",
    noRegions: "No hay regiones disponibles",
    memberZone: "Zona de miembros",
    regionMemberText: "Desbloquea recomendaciones especiales y promociones exclusivas para miembros.",
    regionNotFound: "Región no encontrada",
    createAccount: "Crear una cuenta",
    removeFavorite: "Quitar de favoritos",
    removedFromFavorites: "Producto eliminado de favoritos.",
    search: "Buscar",
    searchEmpty: "No encontramos coincidencias.",
    searchFamilies: "Familias",
    searchBrands: "Marcas",
    searchCategories: "Categorías",
    searchLoading: "Buscando...",
    searchPlaceholder: "Buscar en {brandName}",
    searchProducts: "Productos",
    searchSuggestion: "Quizá quisiste decir:",
    selectAttributes: "Selecciona atributos",
    selectAttributesBeforeCart: "Selecciona los atributos del producto antes de agregarlo al carrito.",
    selectOption: "Elige",
    share: "Compartir",
    stock: "Stock",
    status: "Estado",
    stockAvailableCount: "{count} disponibles",
    onlyAvailableCount: "Solo hay {count} pieza(s) disponibles.",
    wholesaleScales: "Escalas de mayoreo",
    wishlists: "Listas",
    myOrders: "Mis pedidos",
    addressAliasBranchPlaceholder: "Ej. Sucursal Centro",
    addressAliasHomePlaceholder: "Casa",
    addressComplementPlaceholder: "Interior 4B, edificio azul",
    addressContactPlaceholder: "Nombre de quien recibe",
    addressNeighborhoodGenericPlaceholder: "Colonia",
    addressNeighborhoodPlaceholder: "Centro",
    addressStateGenericPlaceholder: "Estado",
    addressStatePlaceholder: "Jalisco",
    addressStreetPlaceholder: "Av. Principal 123",
    backHome: "Volver al inicio",
    backToCart: "Volver al carrito",
    backToLogin: "Volver al login",
    businessPersonAlt: "Persona feliz en su negocio",
    cartExcelAllowedFormats: "Formatos permitidos: `.xlsx` y `.xls`. Usa el layout descargado.",
    cartExcelDownloadStep: "1. Descargar layout",
    cartExcelEditableSheetHelp: "Llena sólo `sku` y `quantity`.",
    cartExcelEyebrow: "Carrito por Excel",
    cartExcelImportInfoAdd: "Se agregan al carrito actual.",
    cartExcelImportInfoGroup: "Los SKUs repetidos se agrupan y suman.",
    cartExcelImportInfoRead: "Se lee la hoja `CargaCarrito`.",
    cartExcelImportInfoRecalculate: "Se recalculan promociones y totales al final.",
    cartExcelImportInfoTitle: "Qué sucede al importar",
    cartExcelLayoutDownloadError: "No fue posible descargar el layout de Excel.",
    cartExcelLayoutDownloaded: "Layout descargado correctamente.",
    cartExcelLayoutIncludesEnd: "para referencia.",
    cartExcelLayoutIncludesMiddle: "y una hoja de ",
    cartExcelLayoutIncludesStart: "El archivo incluye la hoja ",
    cartExcelPreparing: "Estamos preparando la carga de carrito por Excel.",
    cartExcelProcessError: "No fue posible procesar el archivo Excel.",
    cartExcelProcessed: "Archivo Excel procesado correctamente.",
    cartExcelSelectFile: "Selecciona tu archivo Excel",
    cartExcelSelectFileWarning: "Selecciona un archivo Excel para procesarlo.",
    cartExcelSubtitleEnd: "y sube el archivo para actualizar tu carrito actual.",
    cartExcelSubtitleStart: "Descarga el layout, llena la hoja",
    cartExcelSummaryTitle: "Resumen del proceso",
    cartExcelSupportSheetHelp: "Consulta SKUs, marcas y precios vigentes.",
    cartExcelTitle: "Carga masiva de pedido",
    cartExcelUploadStep: "2. Subir archivo",
    cartExcelUploadText: "Procesamos SKUs repetidos, sumamos cantidades y actualizamos el carrito con promociones recalculadas.",
    cartItems: "Items en carrito",
    cartRecoveredTitle: "Carrito recuperado",
    cartRecoverError: "No fue posible recuperar el carrito.",
    cartRecovering: "Recuperando carrito...",
    checkConditionsAtPurchase: "Consulta condiciones al comprar.",
    checkoutConfirmingPayment: "Confirmando tu pago",
    checkoutConfirmingStripe: "Confirmando pago con Stripe...",
    checkoutLoadingOrder: "Consultando pedido...",
    checkoutOrderDetailUnavailable: "No fue posible cargar el detalle en este momento.",
    checkoutOrderLoadError: "No fue posible consultar el pedido.",
    checkoutPaymentCanceled: "Pago cancelado",
    checkoutPaymentConfirmed: "Pago confirmado correctamente.",
    checkoutPaymentConfirmingWarning: "El pago está en proceso de confirmación. Verifica el estado del pedido en unos momentos.",
    checkoutPaymentInProgress: "Pago en proceso",
    checkoutPaymentNotCompleted: "No se completó el pago",
    checkoutPaymentReceived: "Pago recibido",
    checkoutRecoveredProductsReady: "{count} producto(s) listos para continuar.",
    checkoutRecoveringCartText: "Estamos recuperando tu carrito para que puedas revisar o intentar el pago nuevamente.",
    checkoutStripeValidationText: "Validamos la sesión con Stripe y conservamos el webhook como respaldo de confirmación.",
    closeFullView: "Cerrar vista completa",
    confirmPassword: "Confirmar contraseña",
    create: "Crear",
    creating: "Creando...",
    deleteList: "Eliminar lista",
    deliveryAvailable: "Entrega disponible",
    downloadLayout: "Descargar layout",
    downloading: "Descargando...",
    editableSheet: "Hoja editable",
    editGoogleMapsLink: "Editar link de Google Maps",
    emailInvalid: "Ingresa un correo válido.",
    emailPlaceholder: "cliente@email.com",
    favoritesEmptyText: "Guarda productos desde el catálogo o desde el detalle de cada producto.",
    favoritesEmptyTitle: "Aún no tienes favoritos",
    favoritesLoadError: "No fue posible cargar tus favoritos.",
    forgotPasswordError: "No fue posible solicitar la recuperación.",
    forgotPasswordRemembered: "¿Recordaste tu contraseña?",
    forgotPasswordSuccess: "Si el correo existe, enviaremos instrucciones para recuperar la contraseña.",
    forgotPasswordTitle: "Recupera el acceso a tu cuenta",
    goHome: "Ir al inicio",
    goToMyAccount: "Ir a mi cuenta",
    highTurnover: "Alta rotación",
    importedItems: "Items importados",
    importedRows: "Filas importadas",
    loginNavigation: "Navegación de login",
    loginNoAccount: "¿No tienes cuenta?",
    loginPageTitle: "Entra y continúa comprando para tu negocio",
    loginRecoverCartNotice: "Inicia sesión para recuperar tu carrito.",
    loginRecoverCartText: "Después de iniciar sesión activaremos tu carrito abandonado y te llevaremos de vuelta a compra.",
    loginRecoverCartTitle: "Inicia sesión para recuperar tu carrito",
    loadingLists: "Cargando listas...",
    newList: "Nueva lista",
    newProducts: "Nuevos productos",
    newPassword: "Nueva contraseña",
    nextImage: "Imagen siguiente",
    nextProducts: "Ver productos siguientes",
    noBrand: "Sin marca",
    noSku: "Sin SKU",
    notFoundText: "La página que buscas no existe.",
    passwordMinLength: "Debe tener al menos 8 caracteres.",
    passwordMinPlaceholder: "Mínimo 8 caracteres",
    passwordRequired: "La contraseña es obligatoria.",
    passwordUpdateError: "No fue posible actualizar la contraseña.",
    passwordUpdated: "Contraseña actualizada correctamente.",
    passwordsDoNotMatch: "Las contraseñas no coinciden.",
    payment: "Pago",
    processCart: "Procesar carrito",
    processedRows: "Filas procesadas",
    processing: "Procesando...",
    productsCount: "{count} producto(s)",
    recoveryNavigation: "Navegación de recuperación",
    registerNavigation: "Navegación de registro",
    registerPageTitle: "Crea tu cuenta y compra más rápido para tu negocio",
    removeFromList: "Quitar de lista",
    removeFile: "Quitar archivo",
    repeatPasswordPlaceholder: "Repite tu contraseña",
    rejectedRows: "Filas rechazadas",
    resetLinkInvalid: "El link de recuperación no es válido.",
    resetLinkMissingEmail: "El link no incluye un correo válido.",
    resetNavigation: "Navegación de restablecimiento",
    resetPasswordIntro: "Después podrás",
    resetPasswordIntroSuffix: "con tus nuevos datos.",
    resetPasswordTitle: "Crea una nueva contraseña",
    savedListsCount: "{count} lista(s) guardada(s)",
    savedProductsCount: "{count} producto(s) guardado(s)",
    row: "Fila",
    rowImportError: "No fue posible importar la fila.",
    rows: "Filas",
    searchInterpretation: "Interpretación de búsqueda",
    sendInstructions: "Enviar instrucciones",
    secureCheckout: "Compra segura y protegida",
    shippingAndReturns: "Envío y devoluciones",
    shippingByCoverage: "Envío según cobertura.",
    shopCollection: "Ver colección",
    signUp: "Regístrate",
    skippedRows: "Filas omitidas",
    supportSheet: "Hoja de apoyo",
    tryAgain: "Intentar de nuevo",
    unnamedProduct: "Producto sin nombre",
    updatePassword: "Actualizar contraseña",
    viewUpdatedCart: "Ver carrito actualizado",
    wishlistCreateError: "No fue posible crear la lista.",
    wishlistCreated: "Lista creada correctamente.",
    wishlistDeleteConfirm: "¿Eliminar esta lista?",
    wishlistDeleteError: "No fue posible eliminar la lista.",
    wishlistDeleted: "Lista eliminada correctamente.",
    wishlistEmptyText: "Agrega productos desde el catálogo o el detalle de producto.",
    wishlistEmptyTitle: "Lista vacía",
    wishlistProductRemoveError: "No fue posible quitar el producto.",
    wishlistProductRemoved: "Producto eliminado de la lista.",
    wishlistProductsLoadError: "No fue posible cargar los productos de la lista.",
    wishlistsEmptyShort: "Aún no tienes listas.",
    wishlistsEmptyText: "Crea una lista para guardar productos por ocasión o compra frecuente.",
    wishlistsEmptyTitle: "Aún no tienes listas",
    wishlistsLoadError: "No fue posible cargar tus listas.",
  },
  fr: {
    addToCart: "Ajouter au panier",
    addingToCart: "Ajout...",
    addToWishlist: "Ajouter à une liste",
    askQuestion: "Poser une question",
    attributes: "Attributs",
    automaticInCart: "Automatique dans le panier",
    active: "Actif",
    activePromotions: "Promotions actives",
    appliesPromotions: "Applique les promotions",
    artisanSelectionTitle: "Sélection de nos artisans",
    addedToCart: "Produit ajouté au panier.",
    addedToFavorites: "Produit ajouté aux favoris.",
    addFavorite: "Ajouter aux favoris",
    baseSku: "SKU de base",
    brand: "Marque",
    brands: "Marques",
    cart: "Panier",
    cartAddedProductsMeta: "{products} produits · {pieces} pièces",
    cartAppliedPromotion: "Promo appliquée",
    cartAvailable: "Disponible",
    cartClear: "Vider le panier",
    cartClearing: "Vidage...",
    cartContinueCheckout: "Continuer vers le checkout",
    cartEmptyText: "Vous n'avez pas encore ajouté de produits. Explorez le catalogue et commencez votre commande.",
    cartEmptyTitle: "Votre panier est vide",
    cartGiftPending: "{count} cadeau(x) à choisir",
    cartGiftSelected: "Cadeau choisi",
    cartGoToProducts: "Aller aux produits",
    cartInsufficientStock: "Stock insuffisant",
    cartLoadingText: "Patientez pendant que nous chargeons vos produits.",
    cartLoadingTitle: "Chargement du panier...",
    cartNoProductsFound: "Aucun produit trouvé dans votre panier",
    cartNoProductsFoundText: "Essayez un autre terme ou ajustez votre recherche.",
    cartProcessOrder: "Traiter la commande",
    cartQuickWholesaleOrder: "Commande grossiste rapide",
    cartRegionalSplitsTitle: "Répartition régionale",
    cartRegionalSplitsText: "Répartition estimée par centre régional.",
    cartRegionalSource: "Centre régional : {region}",
    commissionEstimated: "Commission estimée",
    netEstimated: "Net estimé",
    cartRemove: "Supprimer",
    cartRemoveSelection: "Supprimer la sélection",
    cartRemoving: "Suppression...",
    cartReviewAvailability: "Vérifier la disponibilité",
    cartSaveList: "Enregistrer dans une liste",
    cartSearchPlaceholder: "Rechercher dans le panier",
    cartSelectProduct: "Sélectionner {name}",
    cartShowingProducts: "Affichage de {shown} sur {total} produits",
    cartUnitPrice: "Prix unitaire",
    cartClearSuccess: "Panier vidé correctement.",
    cartCouponApplied: "Coupon appliqué au panier",
    cartCouponCodePrompt: "Ajoutez un code promotionnel",
    cartCouponTitle: "Coupon",
    cartInvalidCoupon: "Non valide",
    cartApplyCoupon: "Appliquer",
    cartApplying: "Application...",
    cartRemoveCoupon: "Retirer",
    cartRemovingSelection: "Retrait...",
    cartRecovered: "Panier récupéré correctement.",
    cartRemoveProductError: "Impossible de supprimer le produit.",
    cartRemoveSelectedSuccess: "Produits sélectionnés supprimés correctement.",
    cartRemoveSelectedError: "Impossible de supprimer les produits sélectionnés.",
    cartSelectAtLeastOne: "Sélectionnez au moins un produit.",
    cartGiftChosen: "Cadeau sélectionné correctement.",
    cartGiftChoosePending: "Sélectionnez votre cadeau en attente avant de continuer.",
    cartGiftAccounting: "{units} cadeau(x) facturé(s) à {unitPrice} chacun ({lineTotal})",
    cartGiftItems: "{units} cadeau(x) promotionnel(s){names}",
    cartGiftAvailable: "Cadeau disponible",
    cartChooseGift: "Choisissez votre cadeau pour compléter cette promotion.",
    cartSelectedGiftLabel: "Cadeau sélectionné",
    cartGiftSku: "SKU cadeau #{sku} · Quantité {quantity}",
    cartGiftSkuAdded: "Le SKU cadeau est déjà dans votre panier.",
    cartAddGift: "Ajouter le cadeau",
    cartAddingGift: "Ajout...",
    cartRemoveGiftSelection: "Retirer la sélection",
    cartScaleApplied: "Palier appliqué",
    cartScaleAvailable: "Paliers disponibles",
    cartScaleMax: "Vous êtes au palier grossiste maximal pour ce produit.",
    cartScaleNext: "Palier suivant : {discount}.",
    cartScaleMissing: "Ajoutez {count} pièce(s) de plus pour {discount}.",
    cartScaleRangeFrom: "À partir de {from} pcs.",
    cartScaleRangeExact: "{from} pcs.",
    cartScaleRangeBetween: "{from} à {to} pcs.",
    cashback: "Cashback",
    cashbackApplied: "Cashback appliqué",
    cashbackAvailable: "Cashback disponible",
    cashbackEarn: "Cashback à gagner",
    checkoutAcceptTerms: "J'accepte les",
    checkoutAcceptedTermsLink: "conditions générales",
    checkoutAddressChange: "Changer l'adresse",
    checkoutAddressConfigure: "Configurer l'adresse de livraison",
    checkoutAddressCreated: "Adresse créée correctement.",
    checkoutAddressDefault: "Par défaut",
    checkoutAddressDefaultUse: "Utiliser comme adresse par défaut",
    checkoutAddressDeliveryInstructions: "Instructions de livraison",
    checkoutAddressFormAlias: "Alias",
    checkoutAddressFormComplement: "Complément",
    checkoutAddressFormContact: "Contact",
    checkoutAddressFormNeighborhood: "Quartier",
    checkoutAddressFormPhone: "Téléphone",
    checkoutAddressFormState: "État",
    checkoutAddressFormStreet: "Rue et numéro",
    checkoutAddressFormZip: "Code postal",
    checkoutAddressPending: "Adresse en attente",
    checkoutAddressReady: "Adresse prête",
    checkoutAddressSelectedUse: "Utiliser l'adresse sélectionnée",
    checkoutAddressesAvailable: "Adresses disponibles",
    checkoutAddressesEmpty: "Vous n'avez pas d'adresses enregistrées. Ajoutez-en une pour continuer.",
    checkoutAddressesLoading: "Chargement des adresses...",
    checkoutAddAddress: "Ajouter une adresse",
    checkoutAddAnotherAddress: "Ajouter une autre adresse",
    checkoutAmountDue: "Montant à payer",
    checkoutBackToCart: "Retour au panier",
    checkoutBlockersTitle: "Éléments à compléter pour votre commande",
    checkoutCustomer: "Client",
    checkoutCustomerUnknown: "Client non identifié",
    checkoutDetailTitle: "Détail des produits",
    checkoutDownloadPreview: "Télécharger l'aperçu de commande",
    checkoutEmptyText: "Ajoutez des produits pour générer l'aperçu de facture.",
    checkoutGiftAccountingTotal: "Cadeaux facturés",
    checkoutGiftSelectedShort: "Choisi",
    checkoutInvoiceEyebrow: "Aperçu de facture",
    checkoutInvoiceMeta: "Vérifiez les articles, promotions appliquées et le total avant de continuer.",
    checkoutItemsInDocument: "{count} pièce(s) dans le document",
    checkoutLoadingText: "Nous calculons les articles, promotions et totaux.",
    checkoutLoadingTitle: "Chargement de l'aperçu de facture...",
    checkoutNoAppliedPromotions: "Aucune promotion appliquée.",
    checkoutNotesPlaceholder: "Écrivez des notes pour le document ou la commande.",
    checkoutPayStripe: "Payer avec Stripe",
    checkoutPaymentRedirecting: "Redirection...",
    checkoutPaymentValidating: "Validation du checkout...",
    checkoutPdfTitle: "Aperçu de commande #{id}",
    checkoutPdfValidation: "Aperçu de commande pour validation",
    checkoutPendingAddressText: "Sélectionnez ou ajoutez une adresse de livraison pour continuer.",
    checkoutProductNumber: "Produit #{id}",
    checkoutPromotionsAppliedSubtitle: "Réductions calculées par le moteur de promotions",
    checkoutSelectedAddressRemove: "Retirer l'adresse sélectionnée",
    checkoutShipping: "Livraison",
    checkoutSystemNotes: "Notes système",
    checkoutTitle: "Checkout #{id}",
    checkoutTotalToPay: "Total à payer",
    checkoutDocumentNotes: "Notes du document",
    checkoutDocumentNotesText: "Ajoutez une note brève pour cette commande",
    checkoutClose: "Fermer",
    discount: "Réduction",
    firstPurchase: "Premier achat",
    gift: "Cadeau",
    giftPending: "{count} cadeau(x) à choisir",
    giftSelected: "Cadeau choisi",
    loyalty: "Fidélité",
    loyaltyBenefits: "Avantages appliqués à votre compte",
    regular: "Régulier",
    savings: "Économies",
    shippingAddress: "Adresse de livraison",
    subtotal: "Sous-total",
    tax: "Taxes",
    unitPrice: "Prix",
    total: "Total",
    orderSummary: "Résumé de l'achat",
    continueShopping: "Continuer vos achats",
    checkoutStockWarning: "Ajustez les produits avec un stock insuffisant avant de payer.",
    validCashbackAmount: "Saisissez un montant de cashback valide.",
    validCouponCode: "Saisissez un code coupon.",
    couponAppliedSuccess: "Coupon appliqué correctement.",
    couponApplyError: "Impossible d'appliquer le coupon.",
    couponRemovedSuccess: "Coupon retiré du panier.",
    couponRemoveError: "Impossible de retirer le coupon.",
    quantityEmpty: "La quantité ne peut pas être vide.",
    quantityInvalid: "Saisissez une quantité valide.",
    giftSelectionCleared: "Sélection de cadeau supprimée correctement.",
    giftSelectionClearError: "Impossible de supprimer la sélection du cadeau.",
    checkoutAcceptTermsWarning: "Acceptez les conditions générales pour continuer le paiement.",
    checkoutAddressConfigureWarning: "Configurez une adresse de livraison pour continuer.",
    checkoutGiftWarning: "Choisissez votre cadeau avant de continuer le paiement.",
    checkoutCreateOrderError: "Impossible de créer la commande pour démarrer le paiement.",
    checkoutStripeUrlError: "Stripe n'a pas renvoyé d'URL de paiement.",
    checkoutStripeStartError: "Impossible de démarrer le paiement avec Stripe.",
    checkoutLoadAddressError: "Impossible de charger vos adresses.",
    checkoutRecalculateError: "Impossible de recalculer le checkout avec cette adresse.",
    checkoutAddressRequiredFields: "Complétez alias, rue et code postal.",
    checkoutCreateAddressError: "Impossible de créer l'adresse.",
    checkoutPopupWarning: "Autorisez les fenêtres pop-up pour générer l'aperçu PDF.",
    checkoutAddressPanelSubtitle: "Sélectionnez une adresse enregistrée ou ajoutez-en une nouvelle pour continuer.",
    checkoutNoContact: "Sans contact",
    checkoutNoPhone: "Sans téléphone",
    checkoutDeliveryPlaceholder: "Sonner à l'interphone noir. Livrer à la réception.",
    defaultStoreName: "Boutique en ligne",
    checkoutAdjustCart: "Ajuster les quantités dans le panier",
    checkoutPendingGiftText: "Vous devez choisir le cadeau en attente pour continuer.",
    checkoutStockSummaryWarning: "Certains produits n'ont pas assez de stock. Ajustez les quantités dans le panier.",
    checkoutCannotContinue: "Le checkout ne peut pas continuer pour le moment.",
    checkoutPendingGeneric: "Un élément reste à résoudre.",
    checkoutNoAdditionalNotes: "Aucune note supplémentaire.",
    product: "Produit",
    quantityShort: "Qté.",
    saving: "Enregistrement...",
    promoBuySkuGift: "Achetez un SKU et recevez un cadeau",
    promoBrandGiftChoice: "Montant par marque et choix du cadeau",
    promoBrandGiftProduct: "Montant par marque et recevez un SKU",
    promoBuyXGetY: "Achetez X et recevez Y",
    promoBuyXDiscount: "Achetez X et obtenez % de réduction",
    promoDirectDiscount: "Réduction directe",
    promoStrikethrough: "Prix barré",
    promoPriceScale: "Paliers de volume",
    totals: "Totaux",
    accountProfileTitle: "Mes informations",
    accountProfileDescription: "Consultez votre email, numéro client, entreprise et sécurité du compte.",
    accountProfileIntro: "Complétez votre profil commercial, fiscal et de livraison pour garder votre compte prêt.",
    accountProfileLoadError: "Impossible de charger vos informations.",
    accountAddressesTitle: "Mes adresses",
    accountAddressesDescription: "Consultez vos adresses de livraison enregistrées et l'adresse principale.",
    accountAddressesIntro: "Consultez vos adresses de livraison et définissez celle par défaut.",
    accountAddressesLoadingText: "Nous chargeons vos adresses enregistrées.",
    accountAddressesEmptyTitle: "Aucune adresse disponible",
    accountAddressesEmptyText: "Ajoutez une adresse de livraison pour finaliser vos commandes.",
    accountAddressAdded: "Adresse ajoutée correctement.",
    accountAddressUpdated: "Adresse mise à jour correctement.",
    accountAddressSaveError: "Impossible d'enregistrer l'adresse.",
    accountAddressAlreadyDefault: "C'est déjà votre adresse par défaut.",
    accountAddressDefaultUpdated: "Adresse par défaut mise à jour.",
    accountAddressDefaultError: "Impossible de mettre à jour l'adresse par défaut.",
    accountAddressDeleted: "Adresse supprimée correctement.",
    accountAddressDeleteError: "Impossible de supprimer l'adresse.",
    accountAddressDeleteConfirm: "Supprimer l'adresse \"{alias}\" ?",
    accountSavedAddress: "Adresse enregistrée",
    accountNoAlias: "Sans alias",
    accountViewDeliveryInstructions: "Voir les instructions de livraison",
    accountMarkAsDefault: "Marquer par défaut",
    accountEditAddress: "Modifier l'adresse",
    accountAddressModalText: "Complétez les informations de livraison de votre compte.",
    accountSaveAddress: "Enregistrer l'adresse",
    accountOrdersDescription: "Consultez vos achats, paiements, produits, avantages et notes de commande.",
    accountOrdersSummary: "Résumé des commandes",
    accountOrdersLoadError: "Impossible de charger vos commandes.",
    accountOrderDetailLoadError: "Impossible de charger le détail de la commande.",
    accountOrderSearchPlaceholder: "Rechercher par numéro de commande",
    accountOrdersList: "Liste des commandes",
    accountOrdersLoading: "Chargement des commandes...",
    accountOrdersEmpty: "Aucune commande trouvée avec ces filtres.",
    accountSelectOrder: "Sélectionnez une commande",
    accountSelectOrderText: "Ouvrez-la pour voir les produits, l'adresse, les paiements, avantages et notes.",
    accountOrderDetailLoading: "Mise à jour du détail...",
    accountOrderNoProducts: "Cette commande n'a aucun produit enregistré.",
    accountNoAddress: "Aucune adresse enregistrée",
    all: "Tous",
    allPayments: "Tous les paiements",
    apply: "Appliquer",
    change: "Changer",
    city: "Ville",
    company: "Entreprise",
    completeAllFields: "Complétez tous les champs",
    confirm: "Confirmer",
    currentPassword: "Mot de passe actuel",
    currentPasswordPlaceholder: "Saisissez votre mot de passe actuel",
    customer: "Client",
    date: "Date",
    edit: "Modifier",
    from: "De",
    method: "Méthode",
    newPassword: "Nouveau mot de passe",
    newPasswordPlaceholder: "Saisissez votre nouveau mot de passe",
    noAttributes: "Sans attributs",
    noMethod: "Sans méthode",
    noPayment: "Sans paiement",
    notRegistered: "Non enregistré",
    order: "Commande",
    orderCancelled: "Annulée",
    orderDiscount: "Réduction commande",
    orderNotes: "Notes de commande",
    orders: "Commandes",
    other: "Autre",
    paid: "Payé",
    paymentCash: "Espèces",
    paymentCashTransfer: "Espèces et virement",
    paymentCheck: "Chèque",
    paymentFailed: "Échoué",
    paymentMethod: "Méthode de paiement",
    paymentPaid: "Payé",
    paymentPaidPlural: "Payées",
    paymentPending: "En attente",
    paymentTransfer: "Virement bancaire",
    periodTotal: "Total de la période",
    phoneNumber: "Numéro de téléphone",
    shipping: "Livraison",
    showingRange: "Affichage de {from}-{to} sur {total}",
    sortLatest: "Plus récentes",
    sortOldest: "Plus anciennes",
    sortPaidRecent: "Paiements récents",
    sortTotalAsc: "Total le plus bas",
    sortTotalDesc: "Total le plus élevé",
    to: "À",
    cancel: "Annuler",
    saveProfile: "Enregistrer le profil",
    saveAndContinue: "Enregistrer et continuer",
    password: "Mot de passe",
    passwordChangePending: "Changement en attente",
    passwordUpdatedStatus: "Mis à jour",
    passwordMinLength: "Le nouveau mot de passe doit contenir au moins 8 caractères.",
    passwordMismatch: "La confirmation du mot de passe ne correspond pas.",
    passwordMustBeDifferent: "Le nouveau mot de passe doit être différent de l'ancien.",
    passwordUpdating: "Mise à jour du mot de passe...",
    passwordUpdated: "Mot de passe mis à jour correctement.",
    passwordUpdateError: "Impossible de mettre à jour le mot de passe.",
    changePassword: "Changer le mot de passe",
    changeTemporaryPassword: "Changez votre mot de passe temporaire",
    changePasswordText: "Saisissez votre mot de passe actuel et définissez un nouveau mot de passe pour votre compte.",
    confirmPassword: "Confirmer le mot de passe",
    confirmPasswordPlaceholder: "Confirmez votre nouveau mot de passe",
    commercialName: "Nom commercial",
    commercialNameRequired: "Le nom commercial est obligatoire.",
    purchasingContact: "Contact achats",
    quoteEmail: "Email pour devis",
    businessPhone: "Téléphone professionnel",
    secondaryContact: "Contact secondaire",
    secondaryPhone: "Téléphone secondaire",
    businessActivity: "Activité",
    requiresInvoice: "Facture requise",
    fiscalName: "Raison sociale",
    fiscalStreet: "Rue fiscale",
    externalNumber: "No. extérieur",
    internalNumber: "No. intérieur",
    cfdiUse: "Usage CFDI",
    taxCertificatePdf: "Attestation fiscale PDF",
    viewCurrentCertificate: "Voir l'attestation actuelle",
    deliverySameAsFiscal: "L'adresse de livraison est identique à l'adresse fiscale",
    completeFiscalAddress: "Complétez l'adresse fiscale à l'étape précédente.",
    deliverySchedule: "Horaire de livraison",
    deliveryObservations: "Observations de livraison",
    deliveryAddressRequired: "Saisissez l'adresse de livraison ou indiquez qu'elle est identique à l'adresse fiscale.",
    distintivoHHelp: "Correspond au sceau de garantie qu'un établissement respecte pour protéger la santé du consommateur. Exemple : PAS de boîtes en carton mouillées/sales ; PAS de boîtes cabossées, gonflées ou rouillées.",
    pfrCommercialProfile: "Profil commercial",
    pfrCommercialShort: "Commercial",
    pfrCommercialDescription: "Coordonnées, activité et conditions d'achat.",
    pfrFiscalData: "Données fiscales",
    pfrFiscalShort: "Fiscal",
    pfrFiscalDescription: "Raison sociale, RFC, adresse fiscale et attestation.",
    pfrDeliveryDescription: "Adresse, horaires et observations de livraison.",
    pfrStepProgress: "Étape {current} sur {total} · Profil complété à {percent}%",
    pendingFields: "Champs en attente",
    pfrComplete: "Votre profil PFR est complet.",
    pfrPdfRequired: "L'attestation doit être un fichier PDF.",
    pfrSaved: "Profil PFR enregistré correctement.",
    pfrSaveError: "Impossible d'enregistrer le profil PFR.",
    progressSaved: "Progression enregistrée correctement.",
    reviewMarkedFields: "Vérifiez les champs marqués avant de continuer.",
    validCfdiUse: "Sélectionnez un usage CFDI valide.",
    validEmail: "Saisissez un email valide.",
    validPhone: "Saisissez un téléphone valide de 10 à 15 chiffres.",
    validRfc: "Le RFC doit être alphanumérique et comporter 13 ou 14 caractères.",
    validZipCode: "Le code postal doit contenir 5 chiffres.",
    categories: "Catégories",
    category: "Catégorie",
    catalogCategories: "Catégories de produits",
    clearFilters: "Effacer les filtres",
    contact: "Contact",
    contactIntro: "Écrivez-nous pour toute question concernant les commandes, livraisons, inscription client ou informations fournisseurs.",
    contactLocation: "Notre emplacement",
    contactNamePlaceholder: "Jean Dupont",
    currentPromotion: "Promotion active",
    currentPromotions: "promotion(s) active(s)",
    currency: "Devise",
    dailyOffer: "Offre du jour",
    details: "Détails",
    emptyRecentProducts: "Aucun produit récent pour le moment.",
    favorites: "Favoris",
    filters: "Filtres",
    higherPrice: "Prix le plus élevé",
    home: "Accueil",
    inStock: "Stock disponible",
    inactive: "Inactif",
    keyword: "Mot-clé",
    interestedProducts: "Vous pourriez aimer",
    language: "Langue",
    loadingCategories: "Chargement des catégories...",
    loading: "Chargement...",
    name: "Nom",
    nameRequired: "Nom requis",
    email: "Email",
    emailRequired: "Email requis",
    newsletterTitle: "Inscrivez-vous",
    newsletterShortText: "Rejoignez notre communauté, laissez-nous vos coordonnées.",
    newsletterText: "Recevez des promotions, nouveautés et avantages exclusifs directement par email.",
    privacyNotice: "Avis de confidentialité",
    terms: "Conditions générales",
    send: "Envoyer",
    sendMessage: "Envoyer un message",
    sending: "Envoi...",
    description: "Description",
    productDescription: "Description du produit",
    discountSuffix: "de réduction",
    fromPieces: "À partir de {from} pièces",
    pieces: "{count} pièces",
    piecesRange: "De {from} à {to} pièces",
    technicalSheet: "Fiche technique",
    yes: "Oui",
    no: "Non",
    messageRequired: "Message requis",
    faqs: "Questions fréquentes",
    family: "Famille",
    legal: "Mentions légales",
    socialNetworks: "Nos réseaux",
    login: "Se connecter",
    loginToBuy: "Connectez-vous pour acheter",
    loginToSeePrices: "Connectez-vous pour voir les prix",
    lowStock: "Il reste peu de pièces.",
    lowerPrice: "Prix le plus bas",
    logout: "Se déconnecter",
    mostRelevant: "Les plus pertinents",
    monthlyPromotions: "Promotions du mois",
    monthlyPromotionsSubtitle: "Profitez des promotions actives sélectionnées pour votre entreprise.",
    myAccount: "Mon compte",
    noCategories: "Aucune catégorie disponible",
    noProductsFound: "Aucun produit trouvé pour cette recherche.",
    noOfferAvailable: "Aucune offre disponible.",
    noBaseSku: "Aucun SKU de base",
    noStock: "Sans stock",
    notAvailable: "N/A",
    next: "Suivant",
    previous: "Précédent",
    previousImage: "Image précédente",
    add: "Ajouter",
    choosePromotionProduct: "Choisissez un produit de cette promotion pour l'ajouter au panier.",
    results: "résultats",
    resultsFor: "Résultats pour \"{term}\"",
    sortBy: "Trier par",
    mostPopular: "Les plus populaires",
    priceLowToHigh: "Prix : croissant",
    priceHighToLow: "Prix : décroissant",
    nameAsc: "Nom A-Z",
    nameDesc: "Nom Z-A",
    outOfStock: "Produit en rupture de stock",
    offers: "Offres",
    previousOffers: "Voir les offres précédentes",
    seeProducts: "Voir les produits",
    showAllOffers: "Afficher toutes les offres",
    view: "Voir",
    viewFullCollection: "Voir toute la collection",
    viewMore: "Voir plus",
    viewOffer: "Voir l'offre",
    viewFullImage: "Voir l'image complète",
    previousProducts: "Voir les produits précédents",
    popularSearches: "Recherches populaires :",
    popularSearchesRecommended: "Articles recommandés selon vos recherches populaires",
    priceUnavailable: "Prix indisponible",
    productWithoutName: "Produit sans nom",
    productLoading: "Chargement du produit...",
    productNotFound: "Produit introuvable",
    productNotFoundText: "Le produit que vous essayez de consulter n'existe pas ou n'est plus disponible.",
    productPromotions: "Promotions du produit",
    personalProductsSubtitle: "Trouvez l'inspiration avec cette sélection d'articles choisis spécialement pour vous.",
    products: "Produits",
    purchaseInformation: "Informations d'achat",
    quantity: "Quantité",
    itemsCount: "{count} éléments",
    recentPurchases: "Des produits rien que pour vous",
    register: "S'inscrire",
    regions: "Régions",
    noRegions: "Aucune région disponible",
    memberZone: "Espace membres",
    regionMemberText: "Débloquez des recommandations spéciales et des promotions exclusives pour les membres.",
    regionNotFound: "Région introuvable",
    createAccount: "Créer un compte",
    removeFavorite: "Retirer des favoris",
    removedFromFavorites: "Produit retiré des favoris.",
    search: "Rechercher",
    searchEmpty: "Aucun résultat trouvé.",
    searchFamilies: "Familles",
    searchBrands: "Marques",
    searchCategories: "Catégories",
    searchLoading: "Recherche...",
    searchPlaceholder: "Rechercher dans {brandName}",
    searchProducts: "Produits",
    searchSuggestion: "Vouliez-vous dire :",
    selectAttributes: "Sélectionnez les attributs",
    selectAttributesBeforeCart: "Sélectionnez les attributs du produit avant de l'ajouter au panier.",
    selectOption: "Choisir",
    share: "Partager",
    stock: "Stock",
    status: "Statut",
    stockAvailableCount: "{count} disponibles",
    onlyAvailableCount: "Il ne reste que {count} pièce(s).",
    wholesaleScales: "Tarifs de gros",
    wishlists: "Listes",
    myOrders: "Mes commandes",
    addressAliasBranchPlaceholder: "Ex. Succursale Centre",
    addressAliasHomePlaceholder: "Maison",
    addressComplementPlaceholder: "Appartement 4B, bâtiment bleu",
    addressContactPlaceholder: "Nom de la personne qui reçoit",
    addressNeighborhoodGenericPlaceholder: "Quartier",
    addressNeighborhoodPlaceholder: "Centre",
    addressStateGenericPlaceholder: "État",
    addressStatePlaceholder: "Jalisco",
    addressStreetPlaceholder: "Av. Principale 123",
    backHome: "Retour à l'accueil",
    backToCart: "Retour au panier",
    backToLogin: "Retour à la connexion",
    businessPersonAlt: "Personne souriante dans son commerce",
    cartExcelAllowedFormats: "Formats autorisés : `.xlsx` et `.xls`. Utilisez le modèle téléchargé.",
    cartExcelDownloadStep: "1. Télécharger le modèle",
    cartExcelEditableSheetHelp: "Remplissez uniquement `sku` et `quantity`.",
    cartExcelEyebrow: "Panier par Excel",
    cartExcelImportInfoAdd: "Ils sont ajoutés au panier actuel.",
    cartExcelImportInfoGroup: "Les SKUs répétés sont regroupés et additionnés.",
    cartExcelImportInfoRead: "La feuille `CargaCarrito` est lue.",
    cartExcelImportInfoRecalculate: "Les promotions et les totaux sont recalculés à la fin.",
    cartExcelImportInfoTitle: "Ce qui se passe lors de l'importation",
    cartExcelLayoutDownloadError: "Impossible de télécharger le modèle Excel.",
    cartExcelLayoutDownloaded: "Modèle téléchargé correctement.",
    cartExcelLayoutIncludesEnd: "pour référence.",
    cartExcelLayoutIncludesMiddle: "et une feuille ",
    cartExcelLayoutIncludesStart: "Le fichier comprend la feuille ",
    cartExcelPreparing: "Nous préparons le chargement du panier par Excel.",
    cartExcelProcessError: "Impossible de traiter le fichier Excel.",
    cartExcelProcessed: "Fichier Excel traité correctement.",
    cartExcelSelectFile: "Sélectionnez votre fichier Excel",
    cartExcelSelectFileWarning: "Sélectionnez un fichier Excel à traiter.",
    cartExcelSubtitleEnd: "et téléversez le fichier pour mettre à jour votre panier actuel.",
    cartExcelSubtitleStart: "Téléchargez le modèle, remplissez la feuille",
    cartExcelSummaryTitle: "Résumé du processus",
    cartExcelSupportSheetHelp: "Consultez les SKUs, marques et prix en vigueur.",
    cartExcelTitle: "Chargement massif de commande",
    cartExcelUploadStep: "2. Téléverser le fichier",
    cartExcelUploadText: "Nous traitons les SKUs répétés, additionnons les quantités et mettons à jour le panier avec les promotions recalculées.",
    cartItems: "Articles dans le panier",
    cartRecoveredTitle: "Panier récupéré",
    cartRecoverError: "Impossible de récupérer le panier.",
    cartRecovering: "Récupération du panier...",
    checkConditionsAtPurchase: "Consultez les conditions lors de l'achat.",
    checkoutConfirmingPayment: "Confirmation de votre paiement",
    checkoutConfirmingStripe: "Confirmation du paiement avec Stripe...",
    checkoutLoadingOrder: "Consultation de la commande...",
    checkoutOrderDetailUnavailable: "Impossible de charger le détail pour le moment.",
    checkoutOrderLoadError: "Impossible de consulter la commande.",
    checkoutPaymentCanceled: "Paiement annulé",
    checkoutPaymentConfirmed: "Paiement confirmé correctement.",
    checkoutPaymentConfirmingWarning: "Le paiement est en cours de confirmation. Vérifiez l'état de la commande dans quelques instants.",
    checkoutPaymentInProgress: "Paiement en cours",
    checkoutPaymentNotCompleted: "Le paiement n'a pas été complété",
    checkoutPaymentReceived: "Paiement reçu",
    checkoutRecoveredProductsReady: "{count} produit(s) prêts pour continuer.",
    checkoutRecoveringCartText: "Nous récupérons votre panier pour que vous puissiez le vérifier ou réessayer le paiement.",
    checkoutStripeValidationText: "Nous validons la session Stripe et conservons le webhook comme confirmation de secours.",
    closeFullView: "Fermer la vue complète",
    confirmPassword: "Confirmer le mot de passe",
    create: "Créer",
    creating: "Création...",
    deleteList: "Supprimer la liste",
    deliveryAvailable: "Livraison disponible",
    downloadLayout: "Télécharger le modèle",
    downloading: "Téléchargement...",
    editableSheet: "Feuille modifiable",
    editGoogleMapsLink: "Modifier le lien Google Maps",
    emailInvalid: "Saisissez un email valide.",
    emailPlaceholder: "client@email.com",
    favoritesEmptyText: "Enregistrez des produits depuis le catalogue ou la fiche de chaque produit.",
    favoritesEmptyTitle: "Vous n'avez pas encore de favoris",
    favoritesLoadError: "Impossible de charger vos favoris.",
    forgotPasswordError: "Impossible de demander la récupération.",
    forgotPasswordRemembered: "Vous vous souvenez de votre mot de passe ?",
    forgotPasswordSuccess: "Si l'email existe, nous enverrons les instructions pour récupérer le mot de passe.",
    forgotPasswordTitle: "Récupérez l'accès à votre compte",
    goHome: "Aller à l'accueil",
    goToMyAccount: "Aller à mon compte",
    highTurnover: "Forte rotation",
    importedItems: "Articles importés",
    importedRows: "Lignes importées",
    loginNavigation: "Navigation de connexion",
    loginNoAccount: "Vous n'avez pas de compte ?",
    loginPageTitle: "Connectez-vous et continuez vos achats pour votre entreprise",
    loginRecoverCartNotice: "Connectez-vous pour récupérer votre panier.",
    loginRecoverCartText: "Après la connexion, nous activerons votre panier abandonné et vous ramènerons au paiement.",
    loginRecoverCartTitle: "Connectez-vous pour récupérer votre panier",
    loadingLists: "Chargement des listes...",
    newList: "Nouvelle liste",
    newProducts: "Nouveaux produits",
    newPassword: "Nouveau mot de passe",
    nextImage: "Image suivante",
    nextProducts: "Voir les produits suivants",
    noBrand: "Sans marque",
    noSku: "Sans SKU",
    notFoundText: "La page que vous recherchez n'existe pas.",
    passwordMinLength: "Il doit comporter au moins 8 caractères.",
    passwordMinPlaceholder: "Minimum 8 caractères",
    passwordRequired: "Le mot de passe est obligatoire.",
    passwordUpdateError: "Impossible de mettre à jour le mot de passe.",
    passwordUpdated: "Mot de passe mis à jour correctement.",
    passwordsDoNotMatch: "Les mots de passe ne correspondent pas.",
    payment: "Paiement",
    processCart: "Traiter le panier",
    processedRows: "Lignes traitées",
    processing: "Traitement...",
    productsCount: "{count} produit(s)",
    recoveryNavigation: "Navigation de récupération",
    registerNavigation: "Navigation d'inscription",
    registerPageTitle: "Créez votre compte et achetez plus rapidement pour votre entreprise",
    removeFromList: "Retirer de la liste",
    removeFile: "Retirer le fichier",
    repeatPasswordPlaceholder: "Répétez votre mot de passe",
    rejectedRows: "Lignes rejetées",
    resetLinkInvalid: "Le lien de récupération n'est pas valide.",
    resetLinkMissingEmail: "Le lien ne contient pas d'email valide.",
    resetNavigation: "Navigation de réinitialisation",
    resetPasswordIntro: "Ensuite, vous pourrez",
    resetPasswordIntroSuffix: "avec vos nouveaux identifiants.",
    resetPasswordTitle: "Créez un nouveau mot de passe",
    savedListsCount: "{count} liste(s) enregistrée(s)",
    savedProductsCount: "{count} produit(s) enregistré(s)",
    row: "Ligne",
    rowImportError: "Impossible d'importer la ligne.",
    rows: "Lignes",
    searchInterpretation: "Interprétation de recherche",
    sendInstructions: "Envoyer les instructions",
    secureCheckout: "Achat sécurisé et protégé",
    shippingAndReturns: "Livraison et retours",
    shippingByCoverage: "Livraison selon couverture.",
    shopCollection: "Voir la collection",
    signUp: "Inscrivez-vous",
    skippedRows: "Lignes ignorées",
    supportSheet: "Feuille d'aide",
    tryAgain: "Réessayer",
    unnamedProduct: "Produit sans nom",
    updatePassword: "Mettre à jour le mot de passe",
    viewUpdatedCart: "Voir le panier mis à jour",
    wishlistCreateError: "Impossible de créer la liste.",
    wishlistCreated: "Liste créée correctement.",
    wishlistDeleteConfirm: "Supprimer cette liste ?",
    wishlistDeleteError: "Impossible de supprimer la liste.",
    wishlistDeleted: "Liste supprimée correctement.",
    wishlistEmptyText: "Ajoutez des produits depuis le catalogue ou la fiche produit.",
    wishlistEmptyTitle: "Liste vide",
    wishlistProductRemoveError: "Impossible de retirer le produit.",
    wishlistProductRemoved: "Produit retiré de la liste.",
    wishlistProductsLoadError: "Impossible de charger les produits de la liste.",
    wishlistsEmptyShort: "Vous n'avez pas encore de listes.",
    wishlistsEmptyText: "Créez une liste pour enregistrer des produits par occasion ou achat fréquent.",
    wishlistsEmptyTitle: "Vous n'avez pas encore de listes",
    wishlistsLoadError: "Impossible de charger vos listes.",
  },
}

export function getStoredLocale() {
  if (typeof window === "undefined") return ""

  return localStorage.getItem(LOCALE_STORAGE_KEY) || ""
}

export function getCurrentLocale() {
  const storedLocale = getStoredLocale()

  return SUPPORTED_LOCALES.includes(storedLocale) ? storedLocale : DEFAULT_LOCALE
}

export function saveLocale(locale) {
  if (typeof window === "undefined") return
  if (!SUPPORTED_LOCALES.includes(locale)) return

  localStorage.setItem(LOCALE_STORAGE_KEY, locale)
}

export function normalizeLocaleCode(locale) {
  return SUPPORTED_LOCALES.includes(locale) ? locale : DEFAULT_LOCALE
}

export function getLocaleMessages(locale) {
  return messages[normalizeLocaleCode(locale)] || messages[DEFAULT_LOCALE]
}

export function formatMessage(template, values = {}) {
  return String(template || "").replace(/\{(\w+)\}/g, (_, key) => values[key] ?? "")
}

export function isLocalizablePublicPath(url = "") {
  const path = String(url).split("?")[0]

  return isPathInList(path, LOCALIZABLE_PUBLIC_PATHS)
}

export function isLocalizableApiPath(url = "") {
  const path = String(url).split("?")[0]

  return (
    isPathInList(path, LOCALIZABLE_PUBLIC_PATHS) ||
    isPathInList(path, LOCALIZABLE_PRIVATE_PATHS) ||
    isPathInList(path, LOCALIZABLE_AUTH_PATHS)
  )
}

function isPathInList(path, paths) {
  return paths.some((publicPath) => {
    if (path === publicPath) return true
    return path.startsWith(`${publicPath}/`)
  })
}
